#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyInternet.DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyDangKyInternet")]
	public partial class quanlydangkyinternetDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCTGOICUOC(CTGOICUOC instance);
    partial void UpdateCTGOICUOC(CTGOICUOC instance);
    partial void DeleteCTGOICUOC(CTGOICUOC instance);
    partial void InsertTHONGTINTRUYCAP(THONGTINTRUYCAP instance);
    partial void UpdateTHONGTINTRUYCAP(THONGTINTRUYCAP instance);
    partial void DeleteTHONGTINTRUYCAP(THONGTINTRUYCAP instance);
    partial void InsertCTKM(CTKM instance);
    partial void UpdateCTKM(CTKM instance);
    partial void DeleteCTKM(CTKM instance);
    partial void InsertDOITUONG(DOITUONG instance);
    partial void UpdateDOITUONG(DOITUONG instance);
    partial void DeleteDOITUONG(DOITUONG instance);
    partial void InsertDOTUONGAPDUNGKM(DOTUONGAPDUNGKM instance);
    partial void UpdateDOTUONGAPDUNGKM(DOTUONGAPDUNGKM instance);
    partial void DeleteDOTUONGAPDUNGKM(DOTUONGAPDUNGKM instance);
    partial void InsertGOICUOC(GOICUOC instance);
    partial void UpdateGOICUOC(GOICUOC instance);
    partial void DeleteGOICUOC(GOICUOC instance);
    partial void InsertHOADONTHANG(HOADONTHANG instance);
    partial void UpdateHOADONTHANG(HOADONTHANG instance);
    partial void DeleteHOADONTHANG(HOADONTHANG instance);
    partial void InsertHOPDONG(HOPDONG instance);
    partial void UpdateHOPDONG(HOPDONG instance);
    partial void DeleteHOPDONG(HOPDONG instance);
    partial void InsertLOAIGIOTRUYCAP(LOAIGIOTRUYCAP instance);
    partial void UpdateLOAIGIOTRUYCAP(LOAIGIOTRUYCAP instance);
    partial void DeleteLOAIGIOTRUYCAP(LOAIGIOTRUYCAP instance);
    partial void InsertTINHTRANG(TINHTRANG instance);
    partial void UpdateTINHTRANG(TINHTRANG instance);
    partial void DeleteTINHTRANG(TINHTRANG instance);
    #endregion
		
		public quanlydangkyinternetDataContext() : 
				base(global::QuanLyInternet.Properties.Settings.Default.QuanLyDangKyInternetConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public quanlydangkyinternetDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public quanlydangkyinternetDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public quanlydangkyinternetDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public quanlydangkyinternetDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CTGOICUOC> CTGOICUOCs
		{
			get
			{
				return this.GetTable<CTGOICUOC>();
			}
		}
		
		public System.Data.Linq.Table<THONGTINTRUYCAP> THONGTINTRUYCAPs
		{
			get
			{
				return this.GetTable<THONGTINTRUYCAP>();
			}
		}
		
		public System.Data.Linq.Table<CTKM> CTKMs
		{
			get
			{
				return this.GetTable<CTKM>();
			}
		}
		
		public System.Data.Linq.Table<DOITUONG> DOITUONGs
		{
			get
			{
				return this.GetTable<DOITUONG>();
			}
		}
		
		public System.Data.Linq.Table<DOTUONGAPDUNGKM> DOTUONGAPDUNGKMs
		{
			get
			{
				return this.GetTable<DOTUONGAPDUNGKM>();
			}
		}
		
		public System.Data.Linq.Table<GOICUOC> GOICUOCs
		{
			get
			{
				return this.GetTable<GOICUOC>();
			}
		}
		
		public System.Data.Linq.Table<HOADONTHANG> HOADONTHANGs
		{
			get
			{
				return this.GetTable<HOADONTHANG>();
			}
		}
		
		public System.Data.Linq.Table<HOPDONG> HOPDONGs
		{
			get
			{
				return this.GetTable<HOPDONG>();
			}
		}
		
		public System.Data.Linq.Table<LOAIGIOTRUYCAP> LOAIGIOTRUYCAPs
		{
			get
			{
				return this.GetTable<LOAIGIOTRUYCAP>();
			}
		}
		
		public System.Data.Linq.Table<TINHTRANG> TINHTRANGs
		{
			get
			{
				return this.GetTable<TINHTRANG>();
			}
		}
		
		public System.Data.Linq.Table<THAMSO> THAMSOs
		{
			get
			{
				return this.GetTable<THAMSO>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getCTGoiCuoc")]
		public ISingleResult<getCTGoiCuocResult> getCTGoiCuoc()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getCTGoiCuocResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getThongTinTruyCap")]
		public ISingleResult<getThongTinTruyCapResult> getThongTinTruyCap()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getThongTinTruyCapResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getCTKM")]
		public ISingleResult<getCTKMResult> getCTKM()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getCTKMResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getDoiTuong")]
		public ISingleResult<getDoiTuongResult> getDoiTuong()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getDoiTuongResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getDoiTuongApDungKM")]
		public ISingleResult<getDoiTuongApDungKMResult> getDoiTuongApDungKM()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getDoiTuongApDungKMResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getGoiCuoc")]
		public ISingleResult<getGoiCuocResult> getGoiCuoc()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getGoiCuocResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getHoaDonThang")]
		public ISingleResult<getHoaDonThangResult> getHoaDonThang()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getHoaDonThangResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getHopDong")]
		public ISingleResult<getHopDongResult> getHopDong()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getHopDongResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getLoaiGioTruyCap")]
		public ISingleResult<getLoaiGioTruyCapResult> getLoaiGioTruyCap()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getLoaiGioTruyCapResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getTinhTrang")]
		public ISingleResult<getTinhTrangResult> getTinhTrang()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getTinhTrangResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getThamSo")]
		public ISingleResult<getThamSoResult> getThamSo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getThamSoResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTGOICUOC")]
	public partial class CTGOICUOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGoiCuoc;
		
		private string _MaLoaiGioTruyCap;
		
		private System.Nullable<double> _DonGia;
		
		private EntityRef<GOICUOC> _GOICUOC;
		
		private EntityRef<LOAIGIOTRUYCAP> _LOAIGIOTRUYCAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGoiCuocChanging(string value);
    partial void OnMaGoiCuocChanged();
    partial void OnMaLoaiGioTruyCapChanging(string value);
    partial void OnMaLoaiGioTruyCapChanged();
    partial void OnDonGiaChanging(System.Nullable<double> value);
    partial void OnDonGiaChanged();
    #endregion
		
		public CTGOICUOC()
		{
			this._GOICUOC = default(EntityRef<GOICUOC>);
			this._LOAIGIOTRUYCAP = default(EntityRef<LOAIGIOTRUYCAP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGoiCuoc", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGoiCuoc
		{
			get
			{
				return this._MaGoiCuoc;
			}
			set
			{
				if ((this._MaGoiCuoc != value))
				{
					if (this._GOICUOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGoiCuocChanging(value);
					this.SendPropertyChanging();
					this._MaGoiCuoc = value;
					this.SendPropertyChanged("MaGoiCuoc");
					this.OnMaGoiCuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiGioTruyCap", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiGioTruyCap
		{
			get
			{
				return this._MaLoaiGioTruyCap;
			}
			set
			{
				if ((this._MaLoaiGioTruyCap != value))
				{
					if (this._LOAIGIOTRUYCAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiGioTruyCapChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiGioTruyCap = value;
					this.SendPropertyChanged("MaLoaiGioTruyCap");
					this.OnMaLoaiGioTruyCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Float")]
		public System.Nullable<double> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GOICUOC_CTGOICUOC", Storage="_GOICUOC", ThisKey="MaGoiCuoc", OtherKey="MaGoiCuoc", IsForeignKey=true)]
		public GOICUOC GOICUOC
		{
			get
			{
				return this._GOICUOC.Entity;
			}
			set
			{
				GOICUOC previousValue = this._GOICUOC.Entity;
				if (((previousValue != value) 
							|| (this._GOICUOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GOICUOC.Entity = null;
						previousValue.CTGOICUOCs.Remove(this);
					}
					this._GOICUOC.Entity = value;
					if ((value != null))
					{
						value.CTGOICUOCs.Add(this);
						this._MaGoiCuoc = value.MaGoiCuoc;
					}
					else
					{
						this._MaGoiCuoc = default(string);
					}
					this.SendPropertyChanged("GOICUOC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIGIOTRUYCAP_CTGOICUOC", Storage="_LOAIGIOTRUYCAP", ThisKey="MaLoaiGioTruyCap", OtherKey="MaLoaiGioTruyCap", IsForeignKey=true)]
		public LOAIGIOTRUYCAP LOAIGIOTRUYCAP
		{
			get
			{
				return this._LOAIGIOTRUYCAP.Entity;
			}
			set
			{
				LOAIGIOTRUYCAP previousValue = this._LOAIGIOTRUYCAP.Entity;
				if (((previousValue != value) 
							|| (this._LOAIGIOTRUYCAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIGIOTRUYCAP.Entity = null;
						previousValue.CTGOICUOCs.Remove(this);
					}
					this._LOAIGIOTRUYCAP.Entity = value;
					if ((value != null))
					{
						value.CTGOICUOCs.Add(this);
						this._MaLoaiGioTruyCap = value.MaLoaiGioTruyCap;
					}
					else
					{
						this._MaLoaiGioTruyCap = default(string);
					}
					this.SendPropertyChanged("LOAIGIOTRUYCAP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THONGTINTRUYCAP")]
	public partial class THONGTINTRUYCAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STT;
		
		private string _MaHopDong;
		
		private System.Nullable<System.DateTime> _NgayTruyCap;
		
		private System.Nullable<System.TimeSpan> _ThoiDiemTruyCap;
		
		private string _DiaChiTruyCap;
		
		private System.Nullable<double> _DungLuongSuDung;
		
		private EntityRef<HOPDONG> _HOPDONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnMaHopDongChanging(string value);
    partial void OnMaHopDongChanged();
    partial void OnNgayTruyCapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTruyCapChanged();
    partial void OnThoiDiemTruyCapChanging(System.Nullable<System.TimeSpan> value);
    partial void OnThoiDiemTruyCapChanged();
    partial void OnDiaChiTruyCapChanging(string value);
    partial void OnDiaChiTruyCapChanged();
    partial void OnDungLuongSuDungChanging(System.Nullable<double> value);
    partial void OnDungLuongSuDungChanged();
    #endregion
		
		public THONGTINTRUYCAP()
		{
			this._HOPDONG = default(EntityRef<HOPDONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHopDong", DbType="VarChar(10)")]
		public string MaHopDong
		{
			get
			{
				return this._MaHopDong;
			}
			set
			{
				if ((this._MaHopDong != value))
				{
					if (this._HOPDONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHopDongChanging(value);
					this.SendPropertyChanging();
					this._MaHopDong = value;
					this.SendPropertyChanged("MaHopDong");
					this.OnMaHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTruyCap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayTruyCap
		{
			get
			{
				return this._NgayTruyCap;
			}
			set
			{
				if ((this._NgayTruyCap != value))
				{
					this.OnNgayTruyCapChanging(value);
					this.SendPropertyChanging();
					this._NgayTruyCap = value;
					this.SendPropertyChanged("NgayTruyCap");
					this.OnNgayTruyCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiDiemTruyCap", DbType="Time")]
		public System.Nullable<System.TimeSpan> ThoiDiemTruyCap
		{
			get
			{
				return this._ThoiDiemTruyCap;
			}
			set
			{
				if ((this._ThoiDiemTruyCap != value))
				{
					this.OnThoiDiemTruyCapChanging(value);
					this.SendPropertyChanging();
					this._ThoiDiemTruyCap = value;
					this.SendPropertyChanged("ThoiDiemTruyCap");
					this.OnThoiDiemTruyCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiTruyCap", DbType="VarChar(50)")]
		public string DiaChiTruyCap
		{
			get
			{
				return this._DiaChiTruyCap;
			}
			set
			{
				if ((this._DiaChiTruyCap != value))
				{
					this.OnDiaChiTruyCapChanging(value);
					this.SendPropertyChanging();
					this._DiaChiTruyCap = value;
					this.SendPropertyChanged("DiaChiTruyCap");
					this.OnDiaChiTruyCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DungLuongSuDung", DbType="Float")]
		public System.Nullable<double> DungLuongSuDung
		{
			get
			{
				return this._DungLuongSuDung;
			}
			set
			{
				if ((this._DungLuongSuDung != value))
				{
					this.OnDungLuongSuDungChanging(value);
					this.SendPropertyChanging();
					this._DungLuongSuDung = value;
					this.SendPropertyChanged("DungLuongSuDung");
					this.OnDungLuongSuDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOPDONG_THONGTINTRUYCAP", Storage="_HOPDONG", ThisKey="MaHopDong", OtherKey="MaHopDong", IsForeignKey=true)]
		public HOPDONG HOPDONG
		{
			get
			{
				return this._HOPDONG.Entity;
			}
			set
			{
				HOPDONG previousValue = this._HOPDONG.Entity;
				if (((previousValue != value) 
							|| (this._HOPDONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOPDONG.Entity = null;
						previousValue.THONGTINTRUYCAPs.Remove(this);
					}
					this._HOPDONG.Entity = value;
					if ((value != null))
					{
						value.THONGTINTRUYCAPs.Add(this);
						this._MaHopDong = value.MaHopDong;
					}
					else
					{
						this._MaHopDong = default(string);
					}
					this.SendPropertyChanged("HOPDONG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTKM")]
	public partial class CTKM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCTKM;
		
		private string _NoiDung;
		
		private System.Nullable<System.DateTime> _TuNgay;
		
		private System.Nullable<System.DateTime> _DenNgay;
		
		private string _MaGoiCuocKhuyenMai;
		
		private System.Nullable<double> _PhiDangKyKhuyenMai;
		
		private EntitySet<DOTUONGAPDUNGKM> _DOTUONGAPDUNGKMs;
		
		private EntityRef<GOICUOC> _GOICUOC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTKMChanging(string value);
    partial void OnMaCTKMChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnTuNgayChanging(System.Nullable<System.DateTime> value);
    partial void OnTuNgayChanged();
    partial void OnDenNgayChanging(System.Nullable<System.DateTime> value);
    partial void OnDenNgayChanged();
    partial void OnMaGoiCuocKhuyenMaiChanging(string value);
    partial void OnMaGoiCuocKhuyenMaiChanged();
    partial void OnPhiDangKyKhuyenMaiChanging(System.Nullable<double> value);
    partial void OnPhiDangKyKhuyenMaiChanged();
    #endregion
		
		public CTKM()
		{
			this._DOTUONGAPDUNGKMs = new EntitySet<DOTUONGAPDUNGKM>(new Action<DOTUONGAPDUNGKM>(this.attach_DOTUONGAPDUNGKMs), new Action<DOTUONGAPDUNGKM>(this.detach_DOTUONGAPDUNGKMs));
			this._GOICUOC = default(EntityRef<GOICUOC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTKM", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCTKM
		{
			get
			{
				return this._MaCTKM;
			}
			set
			{
				if ((this._MaCTKM != value))
				{
					this.OnMaCTKMChanging(value);
					this.SendPropertyChanging();
					this._MaCTKM = value;
					this.SendPropertyChanged("MaCTKM");
					this.OnMaCTKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuNgay", DbType="Date")]
		public System.Nullable<System.DateTime> TuNgay
		{
			get
			{
				return this._TuNgay;
			}
			set
			{
				if ((this._TuNgay != value))
				{
					this.OnTuNgayChanging(value);
					this.SendPropertyChanging();
					this._TuNgay = value;
					this.SendPropertyChanged("TuNgay");
					this.OnTuNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DenNgay", DbType="Date")]
		public System.Nullable<System.DateTime> DenNgay
		{
			get
			{
				return this._DenNgay;
			}
			set
			{
				if ((this._DenNgay != value))
				{
					this.OnDenNgayChanging(value);
					this.SendPropertyChanging();
					this._DenNgay = value;
					this.SendPropertyChanged("DenNgay");
					this.OnDenNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGoiCuocKhuyenMai", DbType="VarChar(10)")]
		public string MaGoiCuocKhuyenMai
		{
			get
			{
				return this._MaGoiCuocKhuyenMai;
			}
			set
			{
				if ((this._MaGoiCuocKhuyenMai != value))
				{
					if (this._GOICUOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGoiCuocKhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._MaGoiCuocKhuyenMai = value;
					this.SendPropertyChanged("MaGoiCuocKhuyenMai");
					this.OnMaGoiCuocKhuyenMaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiDangKyKhuyenMai", DbType="Float")]
		public System.Nullable<double> PhiDangKyKhuyenMai
		{
			get
			{
				return this._PhiDangKyKhuyenMai;
			}
			set
			{
				if ((this._PhiDangKyKhuyenMai != value))
				{
					this.OnPhiDangKyKhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._PhiDangKyKhuyenMai = value;
					this.SendPropertyChanged("PhiDangKyKhuyenMai");
					this.OnPhiDangKyKhuyenMaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CTKM_DOTUONGAPDUNGKM", Storage="_DOTUONGAPDUNGKMs", ThisKey="MaCTKM", OtherKey="MaCTKM")]
		public EntitySet<DOTUONGAPDUNGKM> DOTUONGAPDUNGKMs
		{
			get
			{
				return this._DOTUONGAPDUNGKMs;
			}
			set
			{
				this._DOTUONGAPDUNGKMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GOICUOC_CTKM", Storage="_GOICUOC", ThisKey="MaGoiCuocKhuyenMai", OtherKey="MaGoiCuoc", IsForeignKey=true)]
		public GOICUOC GOICUOC
		{
			get
			{
				return this._GOICUOC.Entity;
			}
			set
			{
				GOICUOC previousValue = this._GOICUOC.Entity;
				if (((previousValue != value) 
							|| (this._GOICUOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GOICUOC.Entity = null;
						previousValue.CTKMs.Remove(this);
					}
					this._GOICUOC.Entity = value;
					if ((value != null))
					{
						value.CTKMs.Add(this);
						this._MaGoiCuocKhuyenMai = value.MaGoiCuoc;
					}
					else
					{
						this._MaGoiCuocKhuyenMai = default(string);
					}
					this.SendPropertyChanged("GOICUOC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DOTUONGAPDUNGKMs(DOTUONGAPDUNGKM entity)
		{
			this.SendPropertyChanging();
			entity.CTKM = this;
		}
		
		private void detach_DOTUONGAPDUNGKMs(DOTUONGAPDUNGKM entity)
		{
			this.SendPropertyChanging();
			entity.CTKM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOITUONG")]
	public partial class DOITUONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDoiTuong;
		
		private System.Nullable<int> _SoThangCanTren;
		
		private System.Nullable<int> _SoThangCanDuoi;
		
		private string _MoTa;
		
		private EntitySet<DOTUONGAPDUNGKM> _DOTUONGAPDUNGKMs;
		
		private EntitySet<HOPDONG> _HOPDONGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDoiTuongChanging(string value);
    partial void OnMaDoiTuongChanged();
    partial void OnSoThangCanTrenChanging(System.Nullable<int> value);
    partial void OnSoThangCanTrenChanged();
    partial void OnSoThangCanDuoiChanging(System.Nullable<int> value);
    partial void OnSoThangCanDuoiChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public DOITUONG()
		{
			this._DOTUONGAPDUNGKMs = new EntitySet<DOTUONGAPDUNGKM>(new Action<DOTUONGAPDUNGKM>(this.attach_DOTUONGAPDUNGKMs), new Action<DOTUONGAPDUNGKM>(this.detach_DOTUONGAPDUNGKMs));
			this._HOPDONGs = new EntitySet<HOPDONG>(new Action<HOPDONG>(this.attach_HOPDONGs), new Action<HOPDONG>(this.detach_HOPDONGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoiTuong", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDoiTuong
		{
			get
			{
				return this._MaDoiTuong;
			}
			set
			{
				if ((this._MaDoiTuong != value))
				{
					this.OnMaDoiTuongChanging(value);
					this.SendPropertyChanging();
					this._MaDoiTuong = value;
					this.SendPropertyChanged("MaDoiTuong");
					this.OnMaDoiTuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoThangCanTren", DbType="Int")]
		public System.Nullable<int> SoThangCanTren
		{
			get
			{
				return this._SoThangCanTren;
			}
			set
			{
				if ((this._SoThangCanTren != value))
				{
					this.OnSoThangCanTrenChanging(value);
					this.SendPropertyChanging();
					this._SoThangCanTren = value;
					this.SendPropertyChanged("SoThangCanTren");
					this.OnSoThangCanTrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoThangCanDuoi", DbType="Int")]
		public System.Nullable<int> SoThangCanDuoi
		{
			get
			{
				return this._SoThangCanDuoi;
			}
			set
			{
				if ((this._SoThangCanDuoi != value))
				{
					this.OnSoThangCanDuoiChanging(value);
					this.SendPropertyChanging();
					this._SoThangCanDuoi = value;
					this.SendPropertyChanged("SoThangCanDuoi");
					this.OnSoThangCanDuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="VarChar(50)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOITUONG_DOTUONGAPDUNGKM", Storage="_DOTUONGAPDUNGKMs", ThisKey="MaDoiTuong", OtherKey="MaDoiTuong")]
		public EntitySet<DOTUONGAPDUNGKM> DOTUONGAPDUNGKMs
		{
			get
			{
				return this._DOTUONGAPDUNGKMs;
			}
			set
			{
				this._DOTUONGAPDUNGKMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOITUONG_HOPDONG", Storage="_HOPDONGs", ThisKey="MaDoiTuong", OtherKey="MaDoiTuong")]
		public EntitySet<HOPDONG> HOPDONGs
		{
			get
			{
				return this._HOPDONGs;
			}
			set
			{
				this._HOPDONGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DOTUONGAPDUNGKMs(DOTUONGAPDUNGKM entity)
		{
			this.SendPropertyChanging();
			entity.DOITUONG = this;
		}
		
		private void detach_DOTUONGAPDUNGKMs(DOTUONGAPDUNGKM entity)
		{
			this.SendPropertyChanging();
			entity.DOITUONG = null;
		}
		
		private void attach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.DOITUONG = this;
		}
		
		private void detach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.DOITUONG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOTUONGAPDUNGKM")]
	public partial class DOTUONGAPDUNGKM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCTKM;
		
		private string _MaDoiTuong;
		
		private EntityRef<CTKM> _CTKM;
		
		private EntityRef<DOITUONG> _DOITUONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTKMChanging(string value);
    partial void OnMaCTKMChanged();
    partial void OnMaDoiTuongChanging(string value);
    partial void OnMaDoiTuongChanged();
    #endregion
		
		public DOTUONGAPDUNGKM()
		{
			this._CTKM = default(EntityRef<CTKM>);
			this._DOITUONG = default(EntityRef<DOITUONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTKM", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCTKM
		{
			get
			{
				return this._MaCTKM;
			}
			set
			{
				if ((this._MaCTKM != value))
				{
					if (this._CTKM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCTKMChanging(value);
					this.SendPropertyChanging();
					this._MaCTKM = value;
					this.SendPropertyChanged("MaCTKM");
					this.OnMaCTKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoiTuong", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDoiTuong
		{
			get
			{
				return this._MaDoiTuong;
			}
			set
			{
				if ((this._MaDoiTuong != value))
				{
					if (this._DOITUONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDoiTuongChanging(value);
					this.SendPropertyChanging();
					this._MaDoiTuong = value;
					this.SendPropertyChanged("MaDoiTuong");
					this.OnMaDoiTuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CTKM_DOTUONGAPDUNGKM", Storage="_CTKM", ThisKey="MaCTKM", OtherKey="MaCTKM", IsForeignKey=true)]
		public CTKM CTKM
		{
			get
			{
				return this._CTKM.Entity;
			}
			set
			{
				CTKM previousValue = this._CTKM.Entity;
				if (((previousValue != value) 
							|| (this._CTKM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CTKM.Entity = null;
						previousValue.DOTUONGAPDUNGKMs.Remove(this);
					}
					this._CTKM.Entity = value;
					if ((value != null))
					{
						value.DOTUONGAPDUNGKMs.Add(this);
						this._MaCTKM = value.MaCTKM;
					}
					else
					{
						this._MaCTKM = default(string);
					}
					this.SendPropertyChanged("CTKM");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOITUONG_DOTUONGAPDUNGKM", Storage="_DOITUONG", ThisKey="MaDoiTuong", OtherKey="MaDoiTuong", IsForeignKey=true)]
		public DOITUONG DOITUONG
		{
			get
			{
				return this._DOITUONG.Entity;
			}
			set
			{
				DOITUONG previousValue = this._DOITUONG.Entity;
				if (((previousValue != value) 
							|| (this._DOITUONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOITUONG.Entity = null;
						previousValue.DOTUONGAPDUNGKMs.Remove(this);
					}
					this._DOITUONG.Entity = value;
					if ((value != null))
					{
						value.DOTUONGAPDUNGKMs.Add(this);
						this._MaDoiTuong = value.MaDoiTuong;
					}
					else
					{
						this._MaDoiTuong = default(string);
					}
					this.SendPropertyChanged("DOITUONG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GOICUOC")]
	public partial class GOICUOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGoiCuoc;
		
		private System.Nullable<double> _TocDo;
		
		private System.Nullable<double> _CuocThueBaoThang;
		
		private System.Nullable<double> _SoMBMienPhi;
		
		private EntitySet<CTGOICUOC> _CTGOICUOCs;
		
		private EntitySet<CTKM> _CTKMs;
		
		private EntitySet<HOPDONG> _HOPDONGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGoiCuocChanging(string value);
    partial void OnMaGoiCuocChanged();
    partial void OnTocDoChanging(System.Nullable<double> value);
    partial void OnTocDoChanged();
    partial void OnCuocThueBaoThangChanging(System.Nullable<double> value);
    partial void OnCuocThueBaoThangChanged();
    partial void OnSoMBMienPhiChanging(System.Nullable<double> value);
    partial void OnSoMBMienPhiChanged();
    #endregion
		
		public GOICUOC()
		{
			this._CTGOICUOCs = new EntitySet<CTGOICUOC>(new Action<CTGOICUOC>(this.attach_CTGOICUOCs), new Action<CTGOICUOC>(this.detach_CTGOICUOCs));
			this._CTKMs = new EntitySet<CTKM>(new Action<CTKM>(this.attach_CTKMs), new Action<CTKM>(this.detach_CTKMs));
			this._HOPDONGs = new EntitySet<HOPDONG>(new Action<HOPDONG>(this.attach_HOPDONGs), new Action<HOPDONG>(this.detach_HOPDONGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGoiCuoc", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGoiCuoc
		{
			get
			{
				return this._MaGoiCuoc;
			}
			set
			{
				if ((this._MaGoiCuoc != value))
				{
					this.OnMaGoiCuocChanging(value);
					this.SendPropertyChanging();
					this._MaGoiCuoc = value;
					this.SendPropertyChanged("MaGoiCuoc");
					this.OnMaGoiCuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TocDo", DbType="Float")]
		public System.Nullable<double> TocDo
		{
			get
			{
				return this._TocDo;
			}
			set
			{
				if ((this._TocDo != value))
				{
					this.OnTocDoChanging(value);
					this.SendPropertyChanging();
					this._TocDo = value;
					this.SendPropertyChanged("TocDo");
					this.OnTocDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuocThueBaoThang", DbType="Float")]
		public System.Nullable<double> CuocThueBaoThang
		{
			get
			{
				return this._CuocThueBaoThang;
			}
			set
			{
				if ((this._CuocThueBaoThang != value))
				{
					this.OnCuocThueBaoThangChanging(value);
					this.SendPropertyChanging();
					this._CuocThueBaoThang = value;
					this.SendPropertyChanged("CuocThueBaoThang");
					this.OnCuocThueBaoThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoMBMienPhi", DbType="Float")]
		public System.Nullable<double> SoMBMienPhi
		{
			get
			{
				return this._SoMBMienPhi;
			}
			set
			{
				if ((this._SoMBMienPhi != value))
				{
					this.OnSoMBMienPhiChanging(value);
					this.SendPropertyChanging();
					this._SoMBMienPhi = value;
					this.SendPropertyChanged("SoMBMienPhi");
					this.OnSoMBMienPhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GOICUOC_CTGOICUOC", Storage="_CTGOICUOCs", ThisKey="MaGoiCuoc", OtherKey="MaGoiCuoc")]
		public EntitySet<CTGOICUOC> CTGOICUOCs
		{
			get
			{
				return this._CTGOICUOCs;
			}
			set
			{
				this._CTGOICUOCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GOICUOC_CTKM", Storage="_CTKMs", ThisKey="MaGoiCuoc", OtherKey="MaGoiCuocKhuyenMai")]
		public EntitySet<CTKM> CTKMs
		{
			get
			{
				return this._CTKMs;
			}
			set
			{
				this._CTKMs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GOICUOC_HOPDONG", Storage="_HOPDONGs", ThisKey="MaGoiCuoc", OtherKey="MaGoiCuoc")]
		public EntitySet<HOPDONG> HOPDONGs
		{
			get
			{
				return this._HOPDONGs;
			}
			set
			{
				this._HOPDONGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTGOICUOCs(CTGOICUOC entity)
		{
			this.SendPropertyChanging();
			entity.GOICUOC = this;
		}
		
		private void detach_CTGOICUOCs(CTGOICUOC entity)
		{
			this.SendPropertyChanging();
			entity.GOICUOC = null;
		}
		
		private void attach_CTKMs(CTKM entity)
		{
			this.SendPropertyChanging();
			entity.GOICUOC = this;
		}
		
		private void detach_CTKMs(CTKM entity)
		{
			this.SendPropertyChanging();
			entity.GOICUOC = null;
		}
		
		private void attach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.GOICUOC = this;
		}
		
		private void detach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.GOICUOC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADONTHANG")]
	public partial class HOADONTHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHoaDon;
		
		private string _MaHopDong;
		
		private System.Nullable<int> _Thang;
		
		private System.Nullable<int> _Nam;
		
		private System.Nullable<System.DateTime> _NgayThanhToan;
		
		private System.Nullable<double> _TongTien;
		
		private EntityRef<HOPDONG> _HOPDONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonChanging(string value);
    partial void OnMaHoaDonChanged();
    partial void OnMaHopDongChanging(string value);
    partial void OnMaHopDongChanged();
    partial void OnThangChanging(System.Nullable<int> value);
    partial void OnThangChanged();
    partial void OnNamChanging(System.Nullable<int> value);
    partial void OnNamChanged();
    partial void OnNgayThanhToanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThanhToanChanged();
    partial void OnTongTienChanging(System.Nullable<double> value);
    partial void OnTongTienChanged();
    #endregion
		
		public HOADONTHANG()
		{
			this._HOPDONG = default(EntityRef<HOPDONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHopDong", DbType="VarChar(10)")]
		public string MaHopDong
		{
			get
			{
				return this._MaHopDong;
			}
			set
			{
				if ((this._MaHopDong != value))
				{
					if (this._HOPDONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHopDongChanging(value);
					this.SendPropertyChanging();
					this._MaHopDong = value;
					this.SendPropertyChanged("MaHopDong");
					this.OnMaHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang", DbType="Int")]
		public System.Nullable<int> Thang
		{
			get
			{
				return this._Thang;
			}
			set
			{
				if ((this._Thang != value))
				{
					this.OnThangChanging(value);
					this.SendPropertyChanging();
					this._Thang = value;
					this.SendPropertyChanged("Thang");
					this.OnThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nam", DbType="Int")]
		public System.Nullable<int> Nam
		{
			get
			{
				return this._Nam;
			}
			set
			{
				if ((this._Nam != value))
				{
					this.OnNamChanging(value);
					this.SendPropertyChanging();
					this._Nam = value;
					this.SendPropertyChanged("Nam");
					this.OnNamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThanhToan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayThanhToan
		{
			get
			{
				return this._NgayThanhToan;
			}
			set
			{
				if ((this._NgayThanhToan != value))
				{
					this.OnNgayThanhToanChanging(value);
					this.SendPropertyChanging();
					this._NgayThanhToan = value;
					this.SendPropertyChanged("NgayThanhToan");
					this.OnNgayThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Float")]
		public System.Nullable<double> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOPDONG_HOADONTHANG", Storage="_HOPDONG", ThisKey="MaHopDong", OtherKey="MaHopDong", IsForeignKey=true)]
		public HOPDONG HOPDONG
		{
			get
			{
				return this._HOPDONG.Entity;
			}
			set
			{
				HOPDONG previousValue = this._HOPDONG.Entity;
				if (((previousValue != value) 
							|| (this._HOPDONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOPDONG.Entity = null;
						previousValue.HOADONTHANGs.Remove(this);
					}
					this._HOPDONG.Entity = value;
					if ((value != null))
					{
						value.HOADONTHANGs.Add(this);
						this._MaHopDong = value.MaHopDong;
					}
					else
					{
						this._MaHopDong = default(string);
					}
					this.SendPropertyChanged("HOPDONG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOPDONG")]
	public partial class HOPDONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHopDong;
		
		private string _HoTen;
		
		private System.Nullable<int> _CMND;
		
		private string _NgheNghiep;
		
		private string _DCNha;
		
		private string _DCCaiDat;
		
		private string _DCThanhToan;
		
		private System.Nullable<int> _SoDienThoai;
		
		private System.Nullable<System.DateTime> _NgayDangKy;
		
		private string _MaDoiTuong;
		
		private string _MaGoiCuoc;
		
		private System.Nullable<System.DateTime> _NgayApDungGoiCuoc;
		
		private System.Nullable<double> _PhiDangKy;
		
		private string _TinhTrang;
		
		private string _Username;
		
		private string _Password;
		
		private string _Email;
		
		private EntitySet<THONGTINTRUYCAP> _THONGTINTRUYCAPs;
		
		private EntitySet<HOADONTHANG> _HOADONTHANGs;
		
		private EntityRef<DOITUONG> _DOITUONG;
		
		private EntityRef<GOICUOC> _GOICUOC;
		
		private EntityRef<TINHTRANG> _TINHTRANG1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHopDongChanging(string value);
    partial void OnMaHopDongChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnCMNDChanging(System.Nullable<int> value);
    partial void OnCMNDChanged();
    partial void OnNgheNghiepChanging(string value);
    partial void OnNgheNghiepChanged();
    partial void OnDCNhaChanging(string value);
    partial void OnDCNhaChanged();
    partial void OnDCCaiDatChanging(string value);
    partial void OnDCCaiDatChanged();
    partial void OnDCThanhToanChanging(string value);
    partial void OnDCThanhToanChanged();
    partial void OnSoDienThoaiChanging(System.Nullable<int> value);
    partial void OnSoDienThoaiChanged();
    partial void OnNgayDangKyChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangKyChanged();
    partial void OnMaDoiTuongChanging(string value);
    partial void OnMaDoiTuongChanged();
    partial void OnMaGoiCuocChanging(string value);
    partial void OnMaGoiCuocChanged();
    partial void OnNgayApDungGoiCuocChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayApDungGoiCuocChanged();
    partial void OnPhiDangKyChanging(System.Nullable<double> value);
    partial void OnPhiDangKyChanged();
    partial void OnTinhTrangChanging(string value);
    partial void OnTinhTrangChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public HOPDONG()
		{
			this._THONGTINTRUYCAPs = new EntitySet<THONGTINTRUYCAP>(new Action<THONGTINTRUYCAP>(this.attach_THONGTINTRUYCAPs), new Action<THONGTINTRUYCAP>(this.detach_THONGTINTRUYCAPs));
			this._HOADONTHANGs = new EntitySet<HOADONTHANG>(new Action<HOADONTHANG>(this.attach_HOADONTHANGs), new Action<HOADONTHANG>(this.detach_HOADONTHANGs));
			this._DOITUONG = default(EntityRef<DOITUONG>);
			this._GOICUOC = default(EntityRef<GOICUOC>);
			this._TINHTRANG1 = default(EntityRef<TINHTRANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHopDong", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHopDong
		{
			get
			{
				return this._MaHopDong;
			}
			set
			{
				if ((this._MaHopDong != value))
				{
					this.OnMaHopDongChanging(value);
					this.SendPropertyChanging();
					this._MaHopDong = value;
					this.SendPropertyChanged("MaHopDong");
					this.OnMaHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="VarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Int")]
		public System.Nullable<int> CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgheNghiep", DbType="VarChar(50)")]
		public string NgheNghiep
		{
			get
			{
				return this._NgheNghiep;
			}
			set
			{
				if ((this._NgheNghiep != value))
				{
					this.OnNgheNghiepChanging(value);
					this.SendPropertyChanging();
					this._NgheNghiep = value;
					this.SendPropertyChanged("NgheNghiep");
					this.OnNgheNghiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCNha", DbType="VarChar(1000)")]
		public string DCNha
		{
			get
			{
				return this._DCNha;
			}
			set
			{
				if ((this._DCNha != value))
				{
					this.OnDCNhaChanging(value);
					this.SendPropertyChanging();
					this._DCNha = value;
					this.SendPropertyChanged("DCNha");
					this.OnDCNhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCCaiDat", DbType="VarChar(1000)")]
		public string DCCaiDat
		{
			get
			{
				return this._DCCaiDat;
			}
			set
			{
				if ((this._DCCaiDat != value))
				{
					this.OnDCCaiDatChanging(value);
					this.SendPropertyChanging();
					this._DCCaiDat = value;
					this.SendPropertyChanged("DCCaiDat");
					this.OnDCCaiDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCThanhToan", DbType="VarChar(1000)")]
		public string DCThanhToan
		{
			get
			{
				return this._DCThanhToan;
			}
			set
			{
				if ((this._DCThanhToan != value))
				{
					this.OnDCThanhToanChanging(value);
					this.SendPropertyChanging();
					this._DCThanhToan = value;
					this.SendPropertyChanged("DCThanhToan");
					this.OnDCThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="Int")]
		public System.Nullable<int> SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDangKy", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDangKy
		{
			get
			{
				return this._NgayDangKy;
			}
			set
			{
				if ((this._NgayDangKy != value))
				{
					this.OnNgayDangKyChanging(value);
					this.SendPropertyChanging();
					this._NgayDangKy = value;
					this.SendPropertyChanged("NgayDangKy");
					this.OnNgayDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoiTuong", DbType="VarChar(10)")]
		public string MaDoiTuong
		{
			get
			{
				return this._MaDoiTuong;
			}
			set
			{
				if ((this._MaDoiTuong != value))
				{
					if (this._DOITUONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDoiTuongChanging(value);
					this.SendPropertyChanging();
					this._MaDoiTuong = value;
					this.SendPropertyChanged("MaDoiTuong");
					this.OnMaDoiTuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGoiCuoc", DbType="VarChar(10)")]
		public string MaGoiCuoc
		{
			get
			{
				return this._MaGoiCuoc;
			}
			set
			{
				if ((this._MaGoiCuoc != value))
				{
					if (this._GOICUOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGoiCuocChanging(value);
					this.SendPropertyChanging();
					this._MaGoiCuoc = value;
					this.SendPropertyChanged("MaGoiCuoc");
					this.OnMaGoiCuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayApDungGoiCuoc", DbType="Date")]
		public System.Nullable<System.DateTime> NgayApDungGoiCuoc
		{
			get
			{
				return this._NgayApDungGoiCuoc;
			}
			set
			{
				if ((this._NgayApDungGoiCuoc != value))
				{
					this.OnNgayApDungGoiCuocChanging(value);
					this.SendPropertyChanging();
					this._NgayApDungGoiCuoc = value;
					this.SendPropertyChanged("NgayApDungGoiCuoc");
					this.OnNgayApDungGoiCuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiDangKy", DbType="Float")]
		public System.Nullable<double> PhiDangKy
		{
			get
			{
				return this._PhiDangKy;
			}
			set
			{
				if ((this._PhiDangKy != value))
				{
					this.OnPhiDangKyChanging(value);
					this.SendPropertyChanging();
					this._PhiDangKy = value;
					this.SendPropertyChanged("PhiDangKy");
					this.OnPhiDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="VarChar(10)")]
		public string TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					if (this._TINHTRANG1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(10)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(30)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(30)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOPDONG_THONGTINTRUYCAP", Storage="_THONGTINTRUYCAPs", ThisKey="MaHopDong", OtherKey="MaHopDong")]
		public EntitySet<THONGTINTRUYCAP> THONGTINTRUYCAPs
		{
			get
			{
				return this._THONGTINTRUYCAPs;
			}
			set
			{
				this._THONGTINTRUYCAPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOPDONG_HOADONTHANG", Storage="_HOADONTHANGs", ThisKey="MaHopDong", OtherKey="MaHopDong")]
		public EntitySet<HOADONTHANG> HOADONTHANGs
		{
			get
			{
				return this._HOADONTHANGs;
			}
			set
			{
				this._HOADONTHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOITUONG_HOPDONG", Storage="_DOITUONG", ThisKey="MaDoiTuong", OtherKey="MaDoiTuong", IsForeignKey=true)]
		public DOITUONG DOITUONG
		{
			get
			{
				return this._DOITUONG.Entity;
			}
			set
			{
				DOITUONG previousValue = this._DOITUONG.Entity;
				if (((previousValue != value) 
							|| (this._DOITUONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOITUONG.Entity = null;
						previousValue.HOPDONGs.Remove(this);
					}
					this._DOITUONG.Entity = value;
					if ((value != null))
					{
						value.HOPDONGs.Add(this);
						this._MaDoiTuong = value.MaDoiTuong;
					}
					else
					{
						this._MaDoiTuong = default(string);
					}
					this.SendPropertyChanged("DOITUONG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GOICUOC_HOPDONG", Storage="_GOICUOC", ThisKey="MaGoiCuoc", OtherKey="MaGoiCuoc", IsForeignKey=true)]
		public GOICUOC GOICUOC
		{
			get
			{
				return this._GOICUOC.Entity;
			}
			set
			{
				GOICUOC previousValue = this._GOICUOC.Entity;
				if (((previousValue != value) 
							|| (this._GOICUOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GOICUOC.Entity = null;
						previousValue.HOPDONGs.Remove(this);
					}
					this._GOICUOC.Entity = value;
					if ((value != null))
					{
						value.HOPDONGs.Add(this);
						this._MaGoiCuoc = value.MaGoiCuoc;
					}
					else
					{
						this._MaGoiCuoc = default(string);
					}
					this.SendPropertyChanged("GOICUOC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TINHTRANG_HOPDONG", Storage="_TINHTRANG1", ThisKey="TinhTrang", OtherKey="MaTinhTrang", IsForeignKey=true)]
		public TINHTRANG TINHTRANG1
		{
			get
			{
				return this._TINHTRANG1.Entity;
			}
			set
			{
				TINHTRANG previousValue = this._TINHTRANG1.Entity;
				if (((previousValue != value) 
							|| (this._TINHTRANG1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TINHTRANG1.Entity = null;
						previousValue.HOPDONGs.Remove(this);
					}
					this._TINHTRANG1.Entity = value;
					if ((value != null))
					{
						value.HOPDONGs.Add(this);
						this._TinhTrang = value.MaTinhTrang;
					}
					else
					{
						this._TinhTrang = default(string);
					}
					this.SendPropertyChanged("TINHTRANG1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THONGTINTRUYCAPs(THONGTINTRUYCAP entity)
		{
			this.SendPropertyChanging();
			entity.HOPDONG = this;
		}
		
		private void detach_THONGTINTRUYCAPs(THONGTINTRUYCAP entity)
		{
			this.SendPropertyChanging();
			entity.HOPDONG = null;
		}
		
		private void attach_HOADONTHANGs(HOADONTHANG entity)
		{
			this.SendPropertyChanging();
			entity.HOPDONG = this;
		}
		
		private void detach_HOADONTHANGs(HOADONTHANG entity)
		{
			this.SendPropertyChanging();
			entity.HOPDONG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIGIOTRUYCAP")]
	public partial class LOAIGIOTRUYCAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiGioTruyCap;
		
		private string _KhoangThoiGian;
		
		private EntitySet<CTGOICUOC> _CTGOICUOCs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiGioTruyCapChanging(string value);
    partial void OnMaLoaiGioTruyCapChanged();
    partial void OnKhoangThoiGianChanging(string value);
    partial void OnKhoangThoiGianChanged();
    #endregion
		
		public LOAIGIOTRUYCAP()
		{
			this._CTGOICUOCs = new EntitySet<CTGOICUOC>(new Action<CTGOICUOC>(this.attach_CTGOICUOCs), new Action<CTGOICUOC>(this.detach_CTGOICUOCs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiGioTruyCap", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiGioTruyCap
		{
			get
			{
				return this._MaLoaiGioTruyCap;
			}
			set
			{
				if ((this._MaLoaiGioTruyCap != value))
				{
					this.OnMaLoaiGioTruyCapChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiGioTruyCap = value;
					this.SendPropertyChanged("MaLoaiGioTruyCap");
					this.OnMaLoaiGioTruyCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoangThoiGian", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string KhoangThoiGian
		{
			get
			{
				return this._KhoangThoiGian;
			}
			set
			{
				if ((this._KhoangThoiGian != value))
				{
					this.OnKhoangThoiGianChanging(value);
					this.SendPropertyChanging();
					this._KhoangThoiGian = value;
					this.SendPropertyChanged("KhoangThoiGian");
					this.OnKhoangThoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIGIOTRUYCAP_CTGOICUOC", Storage="_CTGOICUOCs", ThisKey="MaLoaiGioTruyCap", OtherKey="MaLoaiGioTruyCap")]
		public EntitySet<CTGOICUOC> CTGOICUOCs
		{
			get
			{
				return this._CTGOICUOCs;
			}
			set
			{
				this._CTGOICUOCs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTGOICUOCs(CTGOICUOC entity)
		{
			this.SendPropertyChanging();
			entity.LOAIGIOTRUYCAP = this;
		}
		
		private void detach_CTGOICUOCs(CTGOICUOC entity)
		{
			this.SendPropertyChanging();
			entity.LOAIGIOTRUYCAP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TINHTRANG")]
	public partial class TINHTRANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTinhTrang;
		
		private string _NoiDung;
		
		private EntitySet<HOPDONG> _HOPDONGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTinhTrangChanging(string value);
    partial void OnMaTinhTrangChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    #endregion
		
		public TINHTRANG()
		{
			this._HOPDONGs = new EntitySet<HOPDONG>(new Action<HOPDONG>(this.attach_HOPDONGs), new Action<HOPDONG>(this.detach_HOPDONGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinhTrang", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTinhTrang
		{
			get
			{
				return this._MaTinhTrang;
			}
			set
			{
				if ((this._MaTinhTrang != value))
				{
					this.OnMaTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._MaTinhTrang = value;
					this.SendPropertyChanged("MaTinhTrang");
					this.OnMaTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="VarChar(100)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TINHTRANG_HOPDONG", Storage="_HOPDONGs", ThisKey="MaTinhTrang", OtherKey="TinhTrang")]
		public EntitySet<HOPDONG> HOPDONGs
		{
			get
			{
				return this._HOPDONGs;
			}
			set
			{
				this._HOPDONGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.TINHTRANG1 = this;
		}
		
		private void detach_HOPDONGs(HOPDONG entity)
		{
			this.SendPropertyChanging();
			entity.TINHTRANG1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THAMSO")]
	public partial class THAMSO
	{
		
		private System.Nullable<double> _PhiDangKy;
		
		private System.Nullable<int> _NgayBatDauThuPhi;
		
		private System.Nullable<int> _NgayKetThucThuPhi;
		
		public THAMSO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiDangKy", DbType="Float")]
		public System.Nullable<double> PhiDangKy
		{
			get
			{
				return this._PhiDangKy;
			}
			set
			{
				if ((this._PhiDangKy != value))
				{
					this._PhiDangKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDauThuPhi", DbType="Int")]
		public System.Nullable<int> NgayBatDauThuPhi
		{
			get
			{
				return this._NgayBatDauThuPhi;
			}
			set
			{
				if ((this._NgayBatDauThuPhi != value))
				{
					this._NgayBatDauThuPhi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThucThuPhi", DbType="Int")]
		public System.Nullable<int> NgayKetThucThuPhi
		{
			get
			{
				return this._NgayKetThucThuPhi;
			}
			set
			{
				if ((this._NgayKetThucThuPhi != value))
				{
					this._NgayKetThucThuPhi = value;
				}
			}
		}
	}
	
	public partial class getCTGoiCuocResult
	{
		
		private string _MaGoiCuoc;
		
		private string _MaLoaiGioTruyCap;
		
		private System.Nullable<double> _DonGia;
		
		public getCTGoiCuocResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGoiCuoc", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaGoiCuoc
		{
			get
			{
				return this._MaGoiCuoc;
			}
			set
			{
				if ((this._MaGoiCuoc != value))
				{
					this._MaGoiCuoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiGioTruyCap", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaLoaiGioTruyCap
		{
			get
			{
				return this._MaLoaiGioTruyCap;
			}
			set
			{
				if ((this._MaLoaiGioTruyCap != value))
				{
					this._MaLoaiGioTruyCap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Float")]
		public System.Nullable<double> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this._DonGia = value;
				}
			}
		}
	}
	
	public partial class getThongTinTruyCapResult
	{
		
		private int _STT;
		
		private string _MaHopDong;
		
		private System.Nullable<System.DateTime> _NgayTruyCap;
		
		private System.Nullable<System.TimeSpan> _ThoiDiemTruyCap;
		
		private string _DiaChiTruyCap;
		
		private System.Nullable<double> _DungLuongSuDung;
		
		public getThongTinTruyCapResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int NOT NULL")]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this._STT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHopDong", DbType="VarChar(10)")]
		public string MaHopDong
		{
			get
			{
				return this._MaHopDong;
			}
			set
			{
				if ((this._MaHopDong != value))
				{
					this._MaHopDong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTruyCap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayTruyCap
		{
			get
			{
				return this._NgayTruyCap;
			}
			set
			{
				if ((this._NgayTruyCap != value))
				{
					this._NgayTruyCap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiDiemTruyCap", DbType="Time")]
		public System.Nullable<System.TimeSpan> ThoiDiemTruyCap
		{
			get
			{
				return this._ThoiDiemTruyCap;
			}
			set
			{
				if ((this._ThoiDiemTruyCap != value))
				{
					this._ThoiDiemTruyCap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiTruyCap", DbType="VarChar(50)")]
		public string DiaChiTruyCap
		{
			get
			{
				return this._DiaChiTruyCap;
			}
			set
			{
				if ((this._DiaChiTruyCap != value))
				{
					this._DiaChiTruyCap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DungLuongSuDung", DbType="Float")]
		public System.Nullable<double> DungLuongSuDung
		{
			get
			{
				return this._DungLuongSuDung;
			}
			set
			{
				if ((this._DungLuongSuDung != value))
				{
					this._DungLuongSuDung = value;
				}
			}
		}
	}
	
	public partial class getCTKMResult
	{
		
		private string _MaCTKM;
		
		private string _NoiDung;
		
		private System.Nullable<System.DateTime> _TuNgay;
		
		private System.Nullable<System.DateTime> _DenNgay;
		
		private string _MaGoiCuocKhuyenMai;
		
		private System.Nullable<double> _PhiDangKyKhuyenMai;
		
		public getCTKMResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTKM", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaCTKM
		{
			get
			{
				return this._MaCTKM;
			}
			set
			{
				if ((this._MaCTKM != value))
				{
					this._MaCTKM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this._NoiDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuNgay", DbType="Date")]
		public System.Nullable<System.DateTime> TuNgay
		{
			get
			{
				return this._TuNgay;
			}
			set
			{
				if ((this._TuNgay != value))
				{
					this._TuNgay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DenNgay", DbType="Date")]
		public System.Nullable<System.DateTime> DenNgay
		{
			get
			{
				return this._DenNgay;
			}
			set
			{
				if ((this._DenNgay != value))
				{
					this._DenNgay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGoiCuocKhuyenMai", DbType="VarChar(10)")]
		public string MaGoiCuocKhuyenMai
		{
			get
			{
				return this._MaGoiCuocKhuyenMai;
			}
			set
			{
				if ((this._MaGoiCuocKhuyenMai != value))
				{
					this._MaGoiCuocKhuyenMai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiDangKyKhuyenMai", DbType="Float")]
		public System.Nullable<double> PhiDangKyKhuyenMai
		{
			get
			{
				return this._PhiDangKyKhuyenMai;
			}
			set
			{
				if ((this._PhiDangKyKhuyenMai != value))
				{
					this._PhiDangKyKhuyenMai = value;
				}
			}
		}
	}
	
	public partial class getDoiTuongResult
	{
		
		private string _MaDoiTuong;
		
		private System.Nullable<int> _SoThangCanTren;
		
		private System.Nullable<int> _SoThangCanDuoi;
		
		private string _MoTa;
		
		public getDoiTuongResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoiTuong", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaDoiTuong
		{
			get
			{
				return this._MaDoiTuong;
			}
			set
			{
				if ((this._MaDoiTuong != value))
				{
					this._MaDoiTuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoThangCanTren", DbType="Int")]
		public System.Nullable<int> SoThangCanTren
		{
			get
			{
				return this._SoThangCanTren;
			}
			set
			{
				if ((this._SoThangCanTren != value))
				{
					this._SoThangCanTren = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoThangCanDuoi", DbType="Int")]
		public System.Nullable<int> SoThangCanDuoi
		{
			get
			{
				return this._SoThangCanDuoi;
			}
			set
			{
				if ((this._SoThangCanDuoi != value))
				{
					this._SoThangCanDuoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="VarChar(50)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this._MoTa = value;
				}
			}
		}
	}
	
	public partial class getDoiTuongApDungKMResult
	{
		
		private string _MaCTKM;
		
		private string _MaDoiTuong;
		
		public getDoiTuongApDungKMResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTKM", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaCTKM
		{
			get
			{
				return this._MaCTKM;
			}
			set
			{
				if ((this._MaCTKM != value))
				{
					this._MaCTKM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoiTuong", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaDoiTuong
		{
			get
			{
				return this._MaDoiTuong;
			}
			set
			{
				if ((this._MaDoiTuong != value))
				{
					this._MaDoiTuong = value;
				}
			}
		}
	}
	
	public partial class getGoiCuocResult
	{
		
		private string _MaGoiCuoc;
		
		private System.Nullable<double> _TocDo;
		
		private System.Nullable<double> _CuocThueBaoThang;
		
		private System.Nullable<double> _SoMBMienPhi;
		
		public getGoiCuocResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGoiCuoc", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaGoiCuoc
		{
			get
			{
				return this._MaGoiCuoc;
			}
			set
			{
				if ((this._MaGoiCuoc != value))
				{
					this._MaGoiCuoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TocDo", DbType="Float")]
		public System.Nullable<double> TocDo
		{
			get
			{
				return this._TocDo;
			}
			set
			{
				if ((this._TocDo != value))
				{
					this._TocDo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuocThueBaoThang", DbType="Float")]
		public System.Nullable<double> CuocThueBaoThang
		{
			get
			{
				return this._CuocThueBaoThang;
			}
			set
			{
				if ((this._CuocThueBaoThang != value))
				{
					this._CuocThueBaoThang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoMBMienPhi", DbType="Float")]
		public System.Nullable<double> SoMBMienPhi
		{
			get
			{
				return this._SoMBMienPhi;
			}
			set
			{
				if ((this._SoMBMienPhi != value))
				{
					this._SoMBMienPhi = value;
				}
			}
		}
	}
	
	public partial class getHoaDonThangResult
	{
		
		private string _MaHoaDon;
		
		private string _MaHopDong;
		
		private System.Nullable<int> _Thang;
		
		private System.Nullable<int> _Nam;
		
		private System.Nullable<System.DateTime> _NgayThanhToan;
		
		private System.Nullable<double> _TongTien;
		
		public getHoaDonThangResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					this._MaHoaDon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHopDong", DbType="VarChar(10)")]
		public string MaHopDong
		{
			get
			{
				return this._MaHopDong;
			}
			set
			{
				if ((this._MaHopDong != value))
				{
					this._MaHopDong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang", DbType="Int")]
		public System.Nullable<int> Thang
		{
			get
			{
				return this._Thang;
			}
			set
			{
				if ((this._Thang != value))
				{
					this._Thang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nam", DbType="Int")]
		public System.Nullable<int> Nam
		{
			get
			{
				return this._Nam;
			}
			set
			{
				if ((this._Nam != value))
				{
					this._Nam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThanhToan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayThanhToan
		{
			get
			{
				return this._NgayThanhToan;
			}
			set
			{
				if ((this._NgayThanhToan != value))
				{
					this._NgayThanhToan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Float")]
		public System.Nullable<double> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this._TongTien = value;
				}
			}
		}
	}
	
	public partial class getHopDongResult
	{
		
		private string _MaHopDong;
		
		private string _HoTen;
		
		private System.Nullable<int> _CMND;
		
		private string _NgheNghiep;
		
		private string _DCNha;
		
		private string _DCCaiDat;
		
		private string _DCThanhToan;
		
		private System.Nullable<int> _SoDienThoai;
		
		private System.Nullable<System.DateTime> _NgayDangKy;
		
		private string _MaDoiTuong;
		
		private string _MaGoiCuoc;
		
		private System.Nullable<System.DateTime> _NgayApDungGoiCuoc;
		
		private System.Nullable<double> _PhiDangKy;
		
		private string _TinhTrang;
		
		private string _Username;
		
		private string _Password;
		
		private string _Email;
		
		public getHopDongResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHopDong", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaHopDong
		{
			get
			{
				return this._MaHopDong;
			}
			set
			{
				if ((this._MaHopDong != value))
				{
					this._MaHopDong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="VarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Int")]
		public System.Nullable<int> CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this._CMND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgheNghiep", DbType="VarChar(50)")]
		public string NgheNghiep
		{
			get
			{
				return this._NgheNghiep;
			}
			set
			{
				if ((this._NgheNghiep != value))
				{
					this._NgheNghiep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCNha", DbType="VarChar(1000)")]
		public string DCNha
		{
			get
			{
				return this._DCNha;
			}
			set
			{
				if ((this._DCNha != value))
				{
					this._DCNha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCCaiDat", DbType="VarChar(1000)")]
		public string DCCaiDat
		{
			get
			{
				return this._DCCaiDat;
			}
			set
			{
				if ((this._DCCaiDat != value))
				{
					this._DCCaiDat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCThanhToan", DbType="VarChar(1000)")]
		public string DCThanhToan
		{
			get
			{
				return this._DCThanhToan;
			}
			set
			{
				if ((this._DCThanhToan != value))
				{
					this._DCThanhToan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="Int")]
		public System.Nullable<int> SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this._SoDienThoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDangKy", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDangKy
		{
			get
			{
				return this._NgayDangKy;
			}
			set
			{
				if ((this._NgayDangKy != value))
				{
					this._NgayDangKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoiTuong", DbType="VarChar(10)")]
		public string MaDoiTuong
		{
			get
			{
				return this._MaDoiTuong;
			}
			set
			{
				if ((this._MaDoiTuong != value))
				{
					this._MaDoiTuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGoiCuoc", DbType="VarChar(10)")]
		public string MaGoiCuoc
		{
			get
			{
				return this._MaGoiCuoc;
			}
			set
			{
				if ((this._MaGoiCuoc != value))
				{
					this._MaGoiCuoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayApDungGoiCuoc", DbType="Date")]
		public System.Nullable<System.DateTime> NgayApDungGoiCuoc
		{
			get
			{
				return this._NgayApDungGoiCuoc;
			}
			set
			{
				if ((this._NgayApDungGoiCuoc != value))
				{
					this._NgayApDungGoiCuoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiDangKy", DbType="Float")]
		public System.Nullable<double> PhiDangKy
		{
			get
			{
				return this._PhiDangKy;
			}
			set
			{
				if ((this._PhiDangKy != value))
				{
					this._PhiDangKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="VarChar(10)")]
		public string TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this._TinhTrang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(10)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(30)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(30)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
	}
	
	public partial class getLoaiGioTruyCapResult
	{
		
		private string _MaLoaiGioTruyCap;
		
		private string _KhoangThoiGian;
		
		public getLoaiGioTruyCapResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiGioTruyCap", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaLoaiGioTruyCap
		{
			get
			{
				return this._MaLoaiGioTruyCap;
			}
			set
			{
				if ((this._MaLoaiGioTruyCap != value))
				{
					this._MaLoaiGioTruyCap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoangThoiGian", DbType="NVarChar(50)")]
		public string KhoangThoiGian
		{
			get
			{
				return this._KhoangThoiGian;
			}
			set
			{
				if ((this._KhoangThoiGian != value))
				{
					this._KhoangThoiGian = value;
				}
			}
		}
	}
	
	public partial class getTinhTrangResult
	{
		
		private string _MaTinhTrang;
		
		private string _NoiDung;
		
		public getTinhTrangResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTinhTrang", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaTinhTrang
		{
			get
			{
				return this._MaTinhTrang;
			}
			set
			{
				if ((this._MaTinhTrang != value))
				{
					this._MaTinhTrang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="VarChar(100)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this._NoiDung = value;
				}
			}
		}
	}
	
	public partial class getThamSoResult
	{
		
		private System.Nullable<double> _PhiDangKy;
		
		private System.Nullable<int> _NgayBatDauThuPhi;
		
		private System.Nullable<int> _NgayKetThucThuPhi;
		
		public getThamSoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiDangKy", DbType="Float")]
		public System.Nullable<double> PhiDangKy
		{
			get
			{
				return this._PhiDangKy;
			}
			set
			{
				if ((this._PhiDangKy != value))
				{
					this._PhiDangKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDauThuPhi", DbType="Int")]
		public System.Nullable<int> NgayBatDauThuPhi
		{
			get
			{
				return this._NgayBatDauThuPhi;
			}
			set
			{
				if ((this._NgayBatDauThuPhi != value))
				{
					this._NgayBatDauThuPhi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThucThuPhi", DbType="Int")]
		public System.Nullable<int> NgayKetThucThuPhi
		{
			get
			{
				return this._NgayKetThucThuPhi;
			}
			set
			{
				if ((this._NgayKetThucThuPhi != value))
				{
					this._NgayKetThucThuPhi = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
