<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyDangKyInternet" Class="quanlydangkyinternetDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=THINH;Initial Catalog=QuanLyDangKyInternet;Integrated Security=True" SettingsObjectName="QuanLyInternet.Properties.Settings" SettingsPropertyName="QuanLyDangKyInternetConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CTGOICUOC" Member="CTGOICUOCs">
    <Type Name="CTGOICUOC">
      <Column Name="MaGoiCuoc" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoaiGioTruyCap" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="GOICUOC_CTGOICUOC" Member="GOICUOC" ThisKey="MaGoiCuoc" OtherKey="MaGoiCuoc" Type="GOICUOC" IsForeignKey="true" />
      <Association Name="LOAIGIOTRUYCAP_CTGOICUOC" Member="LOAIGIOTRUYCAP" ThisKey="MaLoaiGioTruyCap" OtherKey="MaLoaiGioTruyCap" Type="LOAIGIOTRUYCAP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THONGTINTRUYCAP" Member="THONGTINTRUYCAPs">
    <Type Name="THONGTINTRUYCAP">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaHopDong" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgayTruyCap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ThoiDiemTruyCap" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="DiaChiTruyCap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DungLuongSuDung" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="HOPDONG_THONGTINTRUYCAP" Member="HOPDONG" ThisKey="MaHopDong" OtherKey="MaHopDong" Type="HOPDONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTKM" Member="CTKMs">
    <Type Name="CTKM">
      <Column Name="MaCTKM" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TuNgay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DenNgay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MaGoiCuocKhuyenMai" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PhiDangKyKhuyenMai" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="CTKM_DOITUONGAPDUNGKM" Member="DOITUONGAPDUNGKMs" ThisKey="MaCTKM" OtherKey="MaCTKM" Type="DOITUONGAPDUNGKM" />
      <Association Name="GOICUOC_CTKM" Member="GOICUOC" ThisKey="MaGoiCuocKhuyenMai" OtherKey="MaGoiCuoc" Type="GOICUOC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DOITUONG" Member="DOITUONGs">
    <Type Name="DOITUONG">
      <Column Name="MaDoiTuong" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoThangCanTren" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoThangCanDuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DOITUONG_DOITUONGAPDUNGKM" Member="DOITUONGAPDUNGKMs" ThisKey="MaDoiTuong" OtherKey="MaDoiTuong" Type="DOITUONGAPDUNGKM" />
      <Association Name="DOITUONG_HOPDONG" Member="HOPDONGs" ThisKey="MaDoiTuong" OtherKey="MaDoiTuong" Type="HOPDONG" />
    </Type>
  </Table>
  <Table Name="dbo.DOITUONGAPDUNGKM" Member="DOITUONGAPDUNGKMs">
    <Type Name="DOITUONGAPDUNGKM">
      <Column Name="MaCTKM" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDoiTuong" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CTKM_DOITUONGAPDUNGKM" Member="CTKM" ThisKey="MaCTKM" OtherKey="MaCTKM" Type="CTKM" IsForeignKey="true" />
      <Association Name="DOITUONG_DOITUONGAPDUNGKM" Member="DOITUONG" ThisKey="MaDoiTuong" OtherKey="MaDoiTuong" Type="DOITUONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GOICUOC" Member="GOICUOCs">
    <Type Name="GOICUOC">
      <Column Name="MaGoiCuoc" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TocDo" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CuocThueBaoThang" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoMBMienPhi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="GOICUOC_CTGOICUOC" Member="CTGOICUOCs" ThisKey="MaGoiCuoc" OtherKey="MaGoiCuoc" Type="CTGOICUOC" />
      <Association Name="GOICUOC_CTKM" Member="CTKMs" ThisKey="MaGoiCuoc" OtherKey="MaGoiCuocKhuyenMai" Type="CTKM" />
      <Association Name="GOICUOC_HOPDONG" Member="HOPDONGs" ThisKey="MaGoiCuoc" OtherKey="MaGoiCuoc" Type="HOPDONG" />
    </Type>
  </Table>
  <Table Name="dbo.HOADONTHANG" Member="HOADONTHANGs">
    <Type Name="HOADONTHANG">
      <Column Name="MaHoaDon" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHopDong" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayThanhToan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="HOPDONG_HOADONTHANG" Member="HOPDONG" ThisKey="MaHopDong" OtherKey="MaHopDong" Type="HOPDONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOPDONG" Member="HOPDONGs">
    <Type Name="HOPDONG">
      <Column Name="MaHopDong" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgheNghiep" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DCNha" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="DCCaiDat" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="DCThanhToan" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgayDangKy" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MaDoiTuong" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaGoiCuoc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgayApDungGoiCuoc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PhiDangKy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="HOPDONG_THONGTINTRUYCAP" Member="THONGTINTRUYCAPs" ThisKey="MaHopDong" OtherKey="MaHopDong" Type="THONGTINTRUYCAP" />
      <Association Name="HOPDONG_HOADONTHANG" Member="HOADONTHANGs" ThisKey="MaHopDong" OtherKey="MaHopDong" Type="HOADONTHANG" />
      <Association Name="DOITUONG_HOPDONG" Member="DOITUONG" ThisKey="MaDoiTuong" OtherKey="MaDoiTuong" Type="DOITUONG" IsForeignKey="true" />
      <Association Name="GOICUOC_HOPDONG" Member="GOICUOC" ThisKey="MaGoiCuoc" OtherKey="MaGoiCuoc" Type="GOICUOC" IsForeignKey="true" />
      <Association Name="TINHTRANG_HOPDONG" Member="TINHTRANG1" ThisKey="TinhTrang" OtherKey="MaTinhTrang" Type="TINHTRANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIGIOTRUYCAP" Member="LOAIGIOTRUYCAPs">
    <Type Name="LOAIGIOTRUYCAP">
      <Column Name="MaLoaiGioTruyCap" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="KhoangThoiGian" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LOAIGIOTRUYCAP_CTGOICUOC" Member="CTGOICUOCs" ThisKey="MaLoaiGioTruyCap" OtherKey="MaLoaiGioTruyCap" Type="CTGOICUOC" />
    </Type>
  </Table>
  <Table Name="dbo.TINHTRANG" Member="TINHTRANGs">
    <Type Name="TINHTRANG">
      <Column Name="MaTinhTrang" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="TINHTRANG_HOPDONG" Member="HOPDONGs" ThisKey="MaTinhTrang" OtherKey="TinhTrang" Type="HOPDONG" />
    </Type>
  </Table>
  <Table Name="dbo.THAMSO" Member="THAMSOs">
    <Type Name="THAMSO">
      <Column Name="PhiDangKy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NgayBatDauThuPhi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayKetThucThuPhi" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.addCTGoiCuoc" Method="addCTGoiCuoc">
    <Parameter Name="magoicuoc" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="maloaigiotruycap" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="dongia" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.searchThongTinTruyCap" Method="searchThongTinTruyCap">
    <Parameter Name="mahopdong" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="searchThongTinTruyCapResult">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaHopDong" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgayTruyCap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ThoiDiemTruyCap" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="DiaChiTruyCap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DungLuongSuDung" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.addCTKM" Method="addCTKM">
    <Parameter Name="MaCTKM" Parameter="maCTKM" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="NoiDung" Parameter="noiDung" Type="System.String" DbType="Text" />
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DenNgay" Parameter="denNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="MaGoiCuocKhuyenMai" Parameter="maGoiCuocKhuyenMai" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="PhiDangKyKhuyenMai" Parameter="phiDangKyKhuyenMai" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addDoiTuong" Method="addDoiTuong">
    <Parameter Name="madoituong" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="mota" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="sothangcantren" Type="System.Int32" DbType="Int" />
    <Parameter Name="sothangcanduoi" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addDoiTuongApDungKM" Method="addDoiTuongApDungKM">
    <Parameter Name="mactkm" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="madoituong" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addGoiCuoc" Method="addGoiCuoc">
    <Parameter Name="MaGoiCuoc" Parameter="maGoiCuoc" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="TocDo" Parameter="tocDo" Type="System.Double" DbType="Float" />
    <Parameter Name="CuocThueBaoThang" Parameter="cuocThueBaoThang" Type="System.Double" DbType="Float" />
    <Parameter Name="SoMBMienPhi" Parameter="soMBMienPhi" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addHoaDonThang" Method="addHoaDonThang">
    <Parameter Name="mahoadon" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="mahopdong" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="thang" Type="System.Int32" DbType="Int" />
    <Parameter Name="nam" Type="System.Int32" DbType="Int" />
    <Parameter Name="ngaythanhtoan" Type="System.DateTime" DbType="Date" />
    <Parameter Name="tongtien" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addHopDong" Method="addHopDong">
    <Parameter Name="MaHopDong" Parameter="maHopDong" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="HoTen" Parameter="hoTen" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CMND" Parameter="cMND" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NgheNghiep" Parameter="ngheNghiep" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DCNha" Parameter="dCNha" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="DCCaiDat" Parameter="dCCaiDat" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="DCThanhToan" Parameter="dCThanhToan" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="SoDienThoai" Parameter="soDienThoai" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NgayDangKy" Parameter="ngayDangKy" Type="System.DateTime" DbType="Date" />
    <Parameter Name="MaDoiTuong" Parameter="maDoiTuong" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="MaGoiCuoc" Parameter="maGoiCuoc" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NgayApDungGoiCuoc" Parameter="ngayApDungGoiCuoc" Type="System.DateTime" DbType="Date" />
    <Parameter Name="PhiDangKy" Parameter="phiDangKy" Type="System.Double" DbType="Float" />
    <Parameter Name="TinhTrang" Parameter="tinhTrang" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addLoaiGioTruyCap" Method="addLoaiGioTruyCap">
    <Parameter Name="maloaigiotruycap" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="khoangthoigian" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addTinhTrang" Method="addTinhTrang">
    <Parameter Name="matinhtrang" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="noidung" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.addThongTinTruyCap" Method="addThongTinTruyCap">
    <Parameter Name="mahopdong" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="ngaytruycap" Type="System.DateTime" DbType="Date" />
    <Parameter Name="thoidiemtruycap" Type="System.TimeSpan" DbType="Time" />
    <Parameter Name="diachitruycap" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="dungluongsudung" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deleteCTGoiCuoc" Method="deleteCTGoiCuoc">
    <Parameter Name="magoicuoc" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="maloaigiotruycap" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deleteCTKM" Method="deleteCTKM">
    <Parameter Name="MaCTKM" Parameter="maCTKM" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deleteDoiTuong" Method="deleteDoiTuong">
    <Parameter Name="madoituong" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deleteDoiTuongApDungKM" Method="deleteDoiTuongApDungKM">
    <Parameter Name="mactkm" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="madoituong" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deleteGoiCuoc" Method="deleteGoiCuoc">
    <Parameter Name="MaGoiCuoc" Parameter="maGoiCuoc" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deleteHoaDonThang" Method="deleteHoaDonThang">
    <Parameter Name="mahoadon" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deleteHopDong" Method="deleteHopDong">
    <Parameter Name="mahopdong" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deleteLoaiGioTruyCap" Method="deleteLoaiGioTruyCap">
    <Parameter Name="maloaigiotruycap" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.deleteTinhTrang" Method="deleteTinhTrang">
    <Parameter Name="matinhtrang" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.editCTGoiCuoc" Method="editCTGoiCuoc">
    <Parameter Name="magoicuoc" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="maloaigiotruycap" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="dongia" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.editCTKM" Method="editCTKM">
    <Parameter Name="MaCTKM" Parameter="maCTKM" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="NoiDung" Parameter="noiDung" Type="System.String" DbType="Text" />
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DenNgay" Parameter="denNgay" Type="System.DateTime" DbType="Date" />
    <Parameter Name="MaGoiCuocKhuyenMai" Parameter="maGoiCuocKhuyenMai" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="PhiDangKyKhuyenMai" Parameter="phiDangKyKhuyenMai" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.editDoiTuong" Method="editDoiTuong">
    <Parameter Name="madoituong" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="mota" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="sothangcantren" Type="System.Int32" DbType="Int" />
    <Parameter Name="sothangcanduoi" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.editDoiTuongApDungKM" Method="editDoiTuongApDungKM">
    <Parameter Name="mactkm" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="madoituong" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.editGoiCuoc" Method="editGoiCuoc">
    <Parameter Name="MaGoiCuoc" Parameter="maGoiCuoc" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="TocDo" Parameter="tocDo" Type="System.Double" DbType="Float" />
    <Parameter Name="CuocThueBaoThang" Parameter="cuocThueBaoThang" Type="System.Double" DbType="Float" />
    <Parameter Name="SoMBMienPhi" Parameter="soMBMienPhi" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.editHoaDonThang" Method="editHoaDonThang">
    <Parameter Name="mahoadon" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="mahopdong" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="thang" Type="System.Int32" DbType="Int" />
    <Parameter Name="nam" Type="System.Int32" DbType="Int" />
    <Parameter Name="ngaythanhtoan" Type="System.DateTime" DbType="Date" />
    <Parameter Name="tongtien" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.editHopDong" Method="editHopDong">
    <Parameter Name="MaHopDong" Parameter="maHopDong" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="HoTen" Parameter="hoTen" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CMND" Parameter="cMND" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NgheNghiep" Parameter="ngheNghiep" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DCNha" Parameter="dCNha" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="DCCaiDat" Parameter="dCCaiDat" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="DCThanhToan" Parameter="dCThanhToan" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="SoDienThoai" Parameter="soDienThoai" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NgayDangKy" Parameter="ngayDangKy" Type="System.DateTime" DbType="Date" />
    <Parameter Name="MaDoiTuong" Parameter="maDoiTuong" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="MaGoiCuoc" Parameter="maGoiCuoc" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NgayApDungGoiCuoc" Parameter="ngayApDungGoiCuoc" Type="System.DateTime" DbType="Date" />
    <Parameter Name="PhiDangKy" Parameter="phiDangKy" Type="System.Double" DbType="Float" />
    <Parameter Name="TinhTrang" Parameter="tinhTrang" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.editLoaiGioTruyCap" Method="editLoaiGioTruyCap">
    <Parameter Name="maloaigiotruycap" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="khoangthoigian" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.editTinhTrang" Method="editTinhTrang">
    <Parameter Name="matinhtrang" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="noidung" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.editThamSo" Method="editThamSo">
    <Parameter Name="phidangky" Type="System.Double" DbType="Float" />
    <Parameter Name="ngaybatdauthuphi" Type="System.Int32" DbType="Int" />
    <Parameter Name="ngayketthucthuphi" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.getCTGoiCuoc" Method="getCTGoiCuoc">
    <ElementType Name="getCTGoiCuocResult">
      <Column Name="MaGoiCuoc" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaLoaiGioTruyCap" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getCTKM" Method="getCTKM">
    <ElementType Name="getCTKMResult">
      <Column Name="MaCTKM" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TuNgay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DenNgay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MaGoiCuocKhuyenMai" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PhiDangKyKhuyenMai" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getCTKMWith" Method="getCTKMWith">
    <Parameter Name="MaCTKM" Parameter="maCTKM" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="getCTKMWithResult">
      <Column Name="MaCTKM" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TuNgay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DenNgay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MaGoiCuocKhuyenMai" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PhiDangKyKhuyenMai" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getDoiTuong" Method="getDoiTuong">
    <ElementType Name="getDoiTuongResult">
      <Column Name="MaDoiTuong" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SoThangCanTren" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoThangCanDuoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getDoiTuongApDungKM" Method="getDoiTuongApDungKM">
    <ElementType Name="getDoiTuongApDungKMResult">
      <Column Name="MaCTKM" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaDoiTuong" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getGoiCuoc" Method="getGoiCuoc">
    <ElementType Name="getGoiCuocResult">
      <Column Name="MaGoiCuoc" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TocDo" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CuocThueBaoThang" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoMBMienPhi" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getGoiCuocWith" Method="getGoiCuocWith">
    <Parameter Name="MaGoiCuoc" Parameter="maGoiCuoc" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="getGoiCuocWithResult">
      <Column Name="MaGoiCuoc" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TocDo" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CuocThueBaoThang" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SoMBMienPhi" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getHoaDonThang" Method="getHoaDonThang">
    <ElementType Name="getHoaDonThangResult">
      <Column Name="MaHoaDon" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaHopDong" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Thang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayThanhToan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getHopDong" Method="getHopDong">
    <ElementType Name="getHopDongResult">
      <Column Name="MaHopDong" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CMND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgheNghiep" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DCNha" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="DCCaiDat" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="DCThanhToan" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayDangKy" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MaDoiTuong" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaGoiCuoc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgayApDungGoiCuoc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PhiDangKy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getLoaiGioTruyCap" Method="getLoaiGioTruyCap">
    <ElementType Name="getLoaiGioTruyCapResult">
      <Column Name="MaLoaiGioTruyCap" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="KhoangThoiGian" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getTinhTrang" Method="getTinhTrang">
    <ElementType Name="getTinhTrangResult">
      <Column Name="MaTinhTrang" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getThamSo" Method="getThamSo">
    <ElementType Name="getThamSoResult">
      <Column Name="PhiDangKy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NgayBatDauThuPhi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayKetThucThuPhi" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getThongTinTruyCap" Method="getThongTinTruyCap">
    <ElementType Name="getThongTinTruyCapResult">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaHopDong" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgayTruyCap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ThoiDiemTruyCap" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="DiaChiTruyCap" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DungLuongSuDung" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.searchHopDong" Method="searchHopDong">
    <Parameter Name="MaHopDong" Parameter="maHopDong" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="HoTen" Parameter="hoTen" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CMND" Parameter="cMND" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NgheNghiep" Parameter="ngheNghiep" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DCNha" Parameter="dCNha" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="DCCaiDat" Parameter="dCCaiDat" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="DCThanhToan" Parameter="dCThanhToan" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="SoDienThoai" Parameter="soDienThoai" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="MaDoiTuong" Parameter="maDoiTuong" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="MaGoiCuoc" Parameter="maGoiCuoc" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TinhTrang" Parameter="tinhTrang" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="searchHopDongResult">
      <Column Name="MaHopDong" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CMND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgheNghiep" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DCNha" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="DCCaiDat" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="DCThanhToan" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayDangKy" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MaDoiTuong" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MaGoiCuoc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgayApDungGoiCuoc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PhiDangKy" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>