#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyInternet.DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyDangKyInternet")]
	public partial class quanlydangkyinternetDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTHONGTTINSUDUNGINTERNET(THONGTTINSUDUNGINTERNET instance);
    partial void UpdateTHONGTTINSUDUNGINTERNET(THONGTTINSUDUNGINTERNET instance);
    partial void DeleteTHONGTTINSUDUNGINTERNET(THONGTTINSUDUNGINTERNET instance);
    partial void InsertHOADON(HOADON instance);
    partial void UpdateHOADON(HOADON instance);
    partial void DeleteHOADON(HOADON instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertTAIKHOAN(TAIKHOAN instance);
    partial void UpdateTAIKHOAN(TAIKHOAN instance);
    partial void DeleteTAIKHOAN(TAIKHOAN instance);
    partial void InsertTTLUUTHONG(TTLUUTHONG instance);
    partial void UpdateTTLUUTHONG(TTLUUTHONG instance);
    partial void DeleteTTLUUTHONG(TTLUUTHONG instance);
    partial void InsertTTTHANHTOAN(TTTHANHTOAN instance);
    partial void UpdateTTTHANHTOAN(TTTHANHTOAN instance);
    partial void DeleteTTTHANHTOAN(TTTHANHTOAN instance);
    #endregion
		
		public quanlydangkyinternetDataContext() : 
				base(global::QuanLyInternet.Properties.Settings.Default.QuanLyDangKyInternetConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public quanlydangkyinternetDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public quanlydangkyinternetDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public quanlydangkyinternetDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public quanlydangkyinternetDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HANGSO> HANGSOs
		{
			get
			{
				return this.GetTable<HANGSO>();
			}
		}
		
		public System.Data.Linq.Table<THONGTTINSUDUNGINTERNET> THONGTTINSUDUNGINTERNETs
		{
			get
			{
				return this.GetTable<THONGTTINSUDUNGINTERNET>();
			}
		}
		
		public System.Data.Linq.Table<HOADON> HOADONs
		{
			get
			{
				return this.GetTable<HOADON>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this.GetTable<TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<TTLUUTHONG> TTLUUTHONGs
		{
			get
			{
				return this.GetTable<TTLUUTHONG>();
			}
		}
		
		public System.Data.Linq.Table<TTTHANHTOAN> TTTHANHTOANs
		{
			get
			{
				return this.GetTable<TTTHANHTOAN>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getHangSo")]
		public ISingleResult<getHangSoResult> getHangSo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getHangSoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getTTThanhToan")]
		public ISingleResult<getTTThanhToanResult> getTTThanhToan()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getTTThanhToanResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getHoaDon")]
		public ISingleResult<getHoaDonResult> getHoaDon()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getHoaDonResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getKhachHang")]
		public ISingleResult<getKhachHangResult> getKhachHang()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getKhachHangResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getTaiKhoan")]
		public ISingleResult<getTaiKhoanResult> getTaiKhoan()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getTaiKhoanResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getTTLuuThong")]
		public ISingleResult<getTTLuuThongResult> getTTLuuThong()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getTTLuuThongResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getTTSuDungInternet")]
		public ISingleResult<getTTSuDungInternetResult> getTTSuDungInternet()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getTTSuDungInternetResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HANGSO")]
	public partial class HANGSO
	{
		
		private System.Nullable<double> _CuocTB;
		
		private System.Nullable<double> _PhiHoaMang;
		
		private System.Nullable<double> _GiaCuoc;
		
		private System.Nullable<int> _NgayTinhCuoc;
		
		public HANGSO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuocTB", DbType="Float")]
		public System.Nullable<double> CuocTB
		{
			get
			{
				return this._CuocTB;
			}
			set
			{
				if ((this._CuocTB != value))
				{
					this._CuocTB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiHoaMang", DbType="Float")]
		public System.Nullable<double> PhiHoaMang
		{
			get
			{
				return this._PhiHoaMang;
			}
			set
			{
				if ((this._PhiHoaMang != value))
				{
					this._PhiHoaMang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaCuoc", DbType="Float")]
		public System.Nullable<double> GiaCuoc
		{
			get
			{
				return this._GiaCuoc;
			}
			set
			{
				if ((this._GiaCuoc != value))
				{
					this._GiaCuoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTinhCuoc", DbType="Int")]
		public System.Nullable<int> NgayTinhCuoc
		{
			get
			{
				return this._NgayTinhCuoc;
			}
			set
			{
				if ((this._NgayTinhCuoc != value))
				{
					this._NgayTinhCuoc = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THONGTTINSUDUNGINTERNET")]
	public partial class THONGTTINSUDUNGINTERNET : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private int _MaTK;
		
		private System.DateTime _ThoiGianBatDau;
		
		private System.Nullable<System.DateTime> _ThoiGianKetThuc;
		
		private System.Nullable<double> _DungLuongSuDung;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnMaTKChanging(int value);
    partial void OnMaTKChanged();
    partial void OnThoiGianBatDauChanging(System.DateTime value);
    partial void OnThoiGianBatDauChanged();
    partial void OnThoiGianKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianKetThucChanged();
    partial void OnDungLuongSuDungChanging(System.Nullable<double> value);
    partial void OnDungLuongSuDungChanged();
    #endregion
		
		public THONGTTINSUDUNGINTERNET()
		{
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaTK
		{
			get
			{
				return this._MaTK;
			}
			set
			{
				if ((this._MaTK != value))
				{
					this.OnMaTKChanging(value);
					this.SendPropertyChanging();
					this._MaTK = value;
					this.SendPropertyChanged("MaTK");
					this.OnMaTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBatDau", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime ThoiGianBatDau
		{
			get
			{
				return this._ThoiGianBatDau;
			}
			set
			{
				if ((this._ThoiGianBatDau != value))
				{
					this.OnThoiGianBatDauChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBatDau = value;
					this.SendPropertyChanged("ThoiGianBatDau");
					this.OnThoiGianBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianKetThuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianKetThuc
		{
			get
			{
				return this._ThoiGianKetThuc;
			}
			set
			{
				if ((this._ThoiGianKetThuc != value))
				{
					this.OnThoiGianKetThucChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianKetThuc = value;
					this.SendPropertyChanged("ThoiGianKetThuc");
					this.OnThoiGianKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DungLuongSuDung", DbType="Float")]
		public System.Nullable<double> DungLuongSuDung
		{
			get
			{
				return this._DungLuongSuDung;
			}
			set
			{
				if ((this._DungLuongSuDung != value))
				{
					this.OnDungLuongSuDungChanging(value);
					this.SendPropertyChanging();
					this._DungLuongSuDung = value;
					this.SendPropertyChanged("DungLuongSuDung");
					this.OnDungLuongSuDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_THONGTTINSUDUNGINTERNET", Storage="_KHACHHANG", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.THONGTTINSUDUNGINTERNETs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.THONGTTINSUDUNGINTERNETs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(int);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON")]
	public partial class HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private int _Thang;
		
		private int _Nam;
		
		private System.Nullable<int> _SoTienThanhToan;
		
		private System.Nullable<System.DateTime> _HanThanhToan;
		
		private System.Nullable<System.DateTime> _NgayThanhToan;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnThangChanging(int value);
    partial void OnThangChanged();
    partial void OnNamChanging(int value);
    partial void OnNamChanged();
    partial void OnSoTienThanhToanChanging(System.Nullable<int> value);
    partial void OnSoTienThanhToanChanged();
    partial void OnHanThanhToanChanging(System.Nullable<System.DateTime> value);
    partial void OnHanThanhToanChanged();
    partial void OnNgayThanhToanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThanhToanChanged();
    #endregion
		
		public HOADON()
		{
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Thang
		{
			get
			{
				return this._Thang;
			}
			set
			{
				if ((this._Thang != value))
				{
					this.OnThangChanging(value);
					this.SendPropertyChanging();
					this._Thang = value;
					this.SendPropertyChanged("Thang");
					this.OnThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nam", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Nam
		{
			get
			{
				return this._Nam;
			}
			set
			{
				if ((this._Nam != value))
				{
					this.OnNamChanging(value);
					this.SendPropertyChanging();
					this._Nam = value;
					this.SendPropertyChanged("Nam");
					this.OnNamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTienThanhToan", DbType="Int")]
		public System.Nullable<int> SoTienThanhToan
		{
			get
			{
				return this._SoTienThanhToan;
			}
			set
			{
				if ((this._SoTienThanhToan != value))
				{
					this.OnSoTienThanhToanChanging(value);
					this.SendPropertyChanging();
					this._SoTienThanhToan = value;
					this.SendPropertyChanged("SoTienThanhToan");
					this.OnSoTienThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanThanhToan", DbType="Date")]
		public System.Nullable<System.DateTime> HanThanhToan
		{
			get
			{
				return this._HanThanhToan;
			}
			set
			{
				if ((this._HanThanhToan != value))
				{
					this.OnHanThanhToanChanging(value);
					this.SendPropertyChanging();
					this._HanThanhToan = value;
					this.SendPropertyChanged("HanThanhToan");
					this.OnHanThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThanhToan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayThanhToan
		{
			get
			{
				return this._NgayThanhToan;
			}
			set
			{
				if ((this._NgayThanhToan != value))
				{
					this.OnNgayThanhToanChanging(value);
					this.SendPropertyChanging();
					this._NgayThanhToan = value;
					this.SendPropertyChanged("NgayThanhToan");
					this.OnNgayThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON", Storage="_KHACHHANG", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(int);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private string _HoTen;
		
		private System.Nullable<int> _CMND;
		
		private string _NgheNghiep;
		
		private string _DCNha;
		
		private string _DCCaiDat;
		
		private string _DCThanhToan;
		
		private System.Nullable<int> _SLTaiKhoan;
		
		private System.Nullable<int> _SoDienThoai;
		
		private System.Nullable<int> _TTLuuThong;
		
		private System.Nullable<int> _TTThanhToan;
		
		private EntitySet<THONGTTINSUDUNGINTERNET> _THONGTTINSUDUNGINTERNETs;
		
		private EntitySet<HOADON> _HOADONs;
		
		private EntitySet<TAIKHOAN> _TAIKHOANs;
		
		private EntityRef<TTLUUTHONG> _TTLUUTHONG1;
		
		private EntityRef<TTTHANHTOAN> _TTTHANHTOAN1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnCMNDChanging(System.Nullable<int> value);
    partial void OnCMNDChanged();
    partial void OnNgheNghiepChanging(string value);
    partial void OnNgheNghiepChanged();
    partial void OnDCNhaChanging(string value);
    partial void OnDCNhaChanged();
    partial void OnDCCaiDatChanging(string value);
    partial void OnDCCaiDatChanged();
    partial void OnDCThanhToanChanging(string value);
    partial void OnDCThanhToanChanged();
    partial void OnSLTaiKhoanChanging(System.Nullable<int> value);
    partial void OnSLTaiKhoanChanged();
    partial void OnSoDienThoaiChanging(System.Nullable<int> value);
    partial void OnSoDienThoaiChanged();
    partial void OnTTLuuThongChanging(System.Nullable<int> value);
    partial void OnTTLuuThongChanged();
    partial void OnTTThanhToanChanging(System.Nullable<int> value);
    partial void OnTTThanhToanChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._THONGTTINSUDUNGINTERNETs = new EntitySet<THONGTTINSUDUNGINTERNET>(new Action<THONGTTINSUDUNGINTERNET>(this.attach_THONGTTINSUDUNGINTERNETs), new Action<THONGTTINSUDUNGINTERNET>(this.detach_THONGTTINSUDUNGINTERNETs));
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			this._TAIKHOANs = new EntitySet<TAIKHOAN>(new Action<TAIKHOAN>(this.attach_TAIKHOANs), new Action<TAIKHOAN>(this.detach_TAIKHOANs));
			this._TTLUUTHONG1 = default(EntityRef<TTLUUTHONG>);
			this._TTTHANHTOAN1 = default(EntityRef<TTTHANHTOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="VarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Int")]
		public System.Nullable<int> CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgheNghiep", DbType="VarChar(50)")]
		public string NgheNghiep
		{
			get
			{
				return this._NgheNghiep;
			}
			set
			{
				if ((this._NgheNghiep != value))
				{
					this.OnNgheNghiepChanging(value);
					this.SendPropertyChanging();
					this._NgheNghiep = value;
					this.SendPropertyChanged("NgheNghiep");
					this.OnNgheNghiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCNha", DbType="VarChar(50)")]
		public string DCNha
		{
			get
			{
				return this._DCNha;
			}
			set
			{
				if ((this._DCNha != value))
				{
					this.OnDCNhaChanging(value);
					this.SendPropertyChanging();
					this._DCNha = value;
					this.SendPropertyChanged("DCNha");
					this.OnDCNhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCCaiDat", DbType="VarChar(50)")]
		public string DCCaiDat
		{
			get
			{
				return this._DCCaiDat;
			}
			set
			{
				if ((this._DCCaiDat != value))
				{
					this.OnDCCaiDatChanging(value);
					this.SendPropertyChanging();
					this._DCCaiDat = value;
					this.SendPropertyChanged("DCCaiDat");
					this.OnDCCaiDatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCThanhToan", DbType="VarChar(50)")]
		public string DCThanhToan
		{
			get
			{
				return this._DCThanhToan;
			}
			set
			{
				if ((this._DCThanhToan != value))
				{
					this.OnDCThanhToanChanging(value);
					this.SendPropertyChanging();
					this._DCThanhToan = value;
					this.SendPropertyChanged("DCThanhToan");
					this.OnDCThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLTaiKhoan", DbType="Int")]
		public System.Nullable<int> SLTaiKhoan
		{
			get
			{
				return this._SLTaiKhoan;
			}
			set
			{
				if ((this._SLTaiKhoan != value))
				{
					this.OnSLTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._SLTaiKhoan = value;
					this.SendPropertyChanged("SLTaiKhoan");
					this.OnSLTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="Int")]
		public System.Nullable<int> SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TTLuuThong", DbType="Int")]
		public System.Nullable<int> TTLuuThong
		{
			get
			{
				return this._TTLuuThong;
			}
			set
			{
				if ((this._TTLuuThong != value))
				{
					if (this._TTLUUTHONG1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTTLuuThongChanging(value);
					this.SendPropertyChanging();
					this._TTLuuThong = value;
					this.SendPropertyChanged("TTLuuThong");
					this.OnTTLuuThongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TTThanhToan", DbType="Int")]
		public System.Nullable<int> TTThanhToan
		{
			get
			{
				return this._TTThanhToan;
			}
			set
			{
				if ((this._TTThanhToan != value))
				{
					if (this._TTTHANHTOAN1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTTThanhToanChanging(value);
					this.SendPropertyChanging();
					this._TTThanhToan = value;
					this.SendPropertyChanged("TTThanhToan");
					this.OnTTThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_THONGTTINSUDUNGINTERNET", Storage="_THONGTTINSUDUNGINTERNETs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<THONGTTINSUDUNGINTERNET> THONGTTINSUDUNGINTERNETs
		{
			get
			{
				return this._THONGTTINSUDUNGINTERNETs;
			}
			set
			{
				this._THONGTTINSUDUNGINTERNETs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON", Storage="_HOADONs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_TAIKHOAN", Storage="_TAIKHOANs", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this._TAIKHOANs;
			}
			set
			{
				this._TAIKHOANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TTLUUTHONG_KHACHHANG", Storage="_TTLUUTHONG1", ThisKey="TTLuuThong", OtherKey="MaTT", IsForeignKey=true)]
		public TTLUUTHONG TTLUUTHONG1
		{
			get
			{
				return this._TTLUUTHONG1.Entity;
			}
			set
			{
				TTLUUTHONG previousValue = this._TTLUUTHONG1.Entity;
				if (((previousValue != value) 
							|| (this._TTLUUTHONG1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TTLUUTHONG1.Entity = null;
						previousValue.KHACHHANGs.Remove(this);
					}
					this._TTLUUTHONG1.Entity = value;
					if ((value != null))
					{
						value.KHACHHANGs.Add(this);
						this._TTLuuThong = value.MaTT;
					}
					else
					{
						this._TTLuuThong = default(Nullable<int>);
					}
					this.SendPropertyChanged("TTLUUTHONG1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TTTHANHTOAN_KHACHHANG", Storage="_TTTHANHTOAN1", ThisKey="TTThanhToan", OtherKey="MaTT", IsForeignKey=true)]
		public TTTHANHTOAN TTTHANHTOAN1
		{
			get
			{
				return this._TTTHANHTOAN1.Entity;
			}
			set
			{
				TTTHANHTOAN previousValue = this._TTTHANHTOAN1.Entity;
				if (((previousValue != value) 
							|| (this._TTTHANHTOAN1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TTTHANHTOAN1.Entity = null;
						previousValue.KHACHHANGs.Remove(this);
					}
					this._TTTHANHTOAN1.Entity = value;
					if ((value != null))
					{
						value.KHACHHANGs.Add(this);
						this._TTThanhToan = value.MaTT;
					}
					else
					{
						this._TTThanhToan = default(Nullable<int>);
					}
					this.SendPropertyChanged("TTTHANHTOAN1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THONGTTINSUDUNGINTERNETs(THONGTTINSUDUNGINTERNET entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_THONGTTINSUDUNGINTERNETs(THONGTTINSUDUNGINTERNET entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
		
		private void attach_TAIKHOANs(TAIKHOAN entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_TAIKHOANs(TAIKHOAN entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN")]
	public partial class TAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private int _MaTK;
		
		private string _MatKhau;
		
		private string _Email;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnMaTKChanging(int value);
    partial void OnMaTKChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public TAIKHOAN()
		{
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaTK
		{
			get
			{
				return this._MaTK;
			}
			set
			{
				if ((this._MaTK != value))
				{
					this.OnMaTKChanging(value);
					this.SendPropertyChanging();
					this._MaTK = value;
					this.SendPropertyChanged("MaTK");
					this.OnMaTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_TAIKHOAN", Storage="_KHACHHANG", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.TAIKHOANs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.TAIKHOANs.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(int);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TTLUUTHONG")]
	public partial class TTLUUTHONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTT;
		
		private string _TenTT;
		
		private EntitySet<KHACHHANG> _KHACHHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTTChanging(int value);
    partial void OnMaTTChanged();
    partial void OnTenTTChanging(string value);
    partial void OnTenTTChanged();
    #endregion
		
		public TTLUUTHONG()
		{
			this._KHACHHANGs = new EntitySet<KHACHHANG>(new Action<KHACHHANG>(this.attach_KHACHHANGs), new Action<KHACHHANG>(this.detach_KHACHHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaTT
		{
			get
			{
				return this._MaTT;
			}
			set
			{
				if ((this._MaTT != value))
				{
					this.OnMaTTChanging(value);
					this.SendPropertyChanging();
					this._MaTT = value;
					this.SendPropertyChanged("MaTT");
					this.OnMaTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTT", DbType="VarChar(50)")]
		public string TenTT
		{
			get
			{
				return this._TenTT;
			}
			set
			{
				if ((this._TenTT != value))
				{
					this.OnTenTTChanging(value);
					this.SendPropertyChanging();
					this._TenTT = value;
					this.SendPropertyChanged("TenTT");
					this.OnTenTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TTLUUTHONG_KHACHHANG", Storage="_KHACHHANGs", ThisKey="MaTT", OtherKey="TTLuuThong")]
		public EntitySet<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this._KHACHHANGs;
			}
			set
			{
				this._KHACHHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.TTLUUTHONG1 = this;
		}
		
		private void detach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.TTLUUTHONG1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TTTHANHTOAN")]
	public partial class TTTHANHTOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTT;
		
		private string _TenTT;
		
		private EntitySet<KHACHHANG> _KHACHHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTTChanging(int value);
    partial void OnMaTTChanged();
    partial void OnTenTTChanging(string value);
    partial void OnTenTTChanged();
    #endregion
		
		public TTTHANHTOAN()
		{
			this._KHACHHANGs = new EntitySet<KHACHHANG>(new Action<KHACHHANG>(this.attach_KHACHHANGs), new Action<KHACHHANG>(this.detach_KHACHHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaTT
		{
			get
			{
				return this._MaTT;
			}
			set
			{
				if ((this._MaTT != value))
				{
					this.OnMaTTChanging(value);
					this.SendPropertyChanging();
					this._MaTT = value;
					this.SendPropertyChanged("MaTT");
					this.OnMaTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTT", DbType="VarChar(50)")]
		public string TenTT
		{
			get
			{
				return this._TenTT;
			}
			set
			{
				if ((this._TenTT != value))
				{
					this.OnTenTTChanging(value);
					this.SendPropertyChanging();
					this._TenTT = value;
					this.SendPropertyChanged("TenTT");
					this.OnTenTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TTTHANHTOAN_KHACHHANG", Storage="_KHACHHANGs", ThisKey="MaTT", OtherKey="TTThanhToan")]
		public EntitySet<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this._KHACHHANGs;
			}
			set
			{
				this._KHACHHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.TTTHANHTOAN1 = this;
		}
		
		private void detach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.TTTHANHTOAN1 = null;
		}
	}
	
	public partial class getHangSoResult
	{
		
		private System.Nullable<double> _CuocTB;
		
		private System.Nullable<double> _PhiHoaMang;
		
		private System.Nullable<double> _GiaCuoc;
		
		private System.Nullable<int> _NgayTinhCuoc;
		
		public getHangSoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuocTB", DbType="Float")]
		public System.Nullable<double> CuocTB
		{
			get
			{
				return this._CuocTB;
			}
			set
			{
				if ((this._CuocTB != value))
				{
					this._CuocTB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiHoaMang", DbType="Float")]
		public System.Nullable<double> PhiHoaMang
		{
			get
			{
				return this._PhiHoaMang;
			}
			set
			{
				if ((this._PhiHoaMang != value))
				{
					this._PhiHoaMang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaCuoc", DbType="Float")]
		public System.Nullable<double> GiaCuoc
		{
			get
			{
				return this._GiaCuoc;
			}
			set
			{
				if ((this._GiaCuoc != value))
				{
					this._GiaCuoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTinhCuoc", DbType="Int")]
		public System.Nullable<int> NgayTinhCuoc
		{
			get
			{
				return this._NgayTinhCuoc;
			}
			set
			{
				if ((this._NgayTinhCuoc != value))
				{
					this._NgayTinhCuoc = value;
				}
			}
		}
	}
	
	public partial class getTTThanhToanResult
	{
		
		private int _MaTT;
		
		private string _TenTT;
		
		public getTTThanhToanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTT", DbType="Int NOT NULL")]
		public int MaTT
		{
			get
			{
				return this._MaTT;
			}
			set
			{
				if ((this._MaTT != value))
				{
					this._MaTT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTT", DbType="VarChar(50)")]
		public string TenTT
		{
			get
			{
				return this._TenTT;
			}
			set
			{
				if ((this._TenTT != value))
				{
					this._TenTT = value;
				}
			}
		}
	}
	
	public partial class getHoaDonResult
	{
		
		private int _MaKH;
		
		private int _Thang;
		
		private int _Nam;
		
		private System.Nullable<int> _SoTienThanhToan;
		
		private System.Nullable<System.DateTime> _HanThanhToan;
		
		private System.Nullable<System.DateTime> _NgayThanhToan;
		
		public getHoaDonResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int NOT NULL")]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this._MaKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thang", DbType="Int NOT NULL")]
		public int Thang
		{
			get
			{
				return this._Thang;
			}
			set
			{
				if ((this._Thang != value))
				{
					this._Thang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nam", DbType="Int NOT NULL")]
		public int Nam
		{
			get
			{
				return this._Nam;
			}
			set
			{
				if ((this._Nam != value))
				{
					this._Nam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTienThanhToan", DbType="Int")]
		public System.Nullable<int> SoTienThanhToan
		{
			get
			{
				return this._SoTienThanhToan;
			}
			set
			{
				if ((this._SoTienThanhToan != value))
				{
					this._SoTienThanhToan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanThanhToan", DbType="Date")]
		public System.Nullable<System.DateTime> HanThanhToan
		{
			get
			{
				return this._HanThanhToan;
			}
			set
			{
				if ((this._HanThanhToan != value))
				{
					this._HanThanhToan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThanhToan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayThanhToan
		{
			get
			{
				return this._NgayThanhToan;
			}
			set
			{
				if ((this._NgayThanhToan != value))
				{
					this._NgayThanhToan = value;
				}
			}
		}
	}
	
	public partial class getKhachHangResult
	{
		
		private int _MaKH;
		
		private string _HoTen;
		
		private System.Nullable<int> _CMND;
		
		private string _NgheNghiep;
		
		private string _DCNha;
		
		private string _DCCaiDat;
		
		private string _DCThanhToan;
		
		private System.Nullable<int> _SLTaiKhoan;
		
		private System.Nullable<int> _SoDienThoai;
		
		private System.Nullable<int> _TTLuuThong;
		
		private System.Nullable<int> _TTThanhToan;
		
		public getKhachHangResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int NOT NULL")]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this._MaKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="VarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Int")]
		public System.Nullable<int> CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this._CMND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgheNghiep", DbType="VarChar(50)")]
		public string NgheNghiep
		{
			get
			{
				return this._NgheNghiep;
			}
			set
			{
				if ((this._NgheNghiep != value))
				{
					this._NgheNghiep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCNha", DbType="VarChar(50)")]
		public string DCNha
		{
			get
			{
				return this._DCNha;
			}
			set
			{
				if ((this._DCNha != value))
				{
					this._DCNha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCCaiDat", DbType="VarChar(50)")]
		public string DCCaiDat
		{
			get
			{
				return this._DCCaiDat;
			}
			set
			{
				if ((this._DCCaiDat != value))
				{
					this._DCCaiDat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCThanhToan", DbType="VarChar(50)")]
		public string DCThanhToan
		{
			get
			{
				return this._DCThanhToan;
			}
			set
			{
				if ((this._DCThanhToan != value))
				{
					this._DCThanhToan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLTaiKhoan", DbType="Int")]
		public System.Nullable<int> SLTaiKhoan
		{
			get
			{
				return this._SLTaiKhoan;
			}
			set
			{
				if ((this._SLTaiKhoan != value))
				{
					this._SLTaiKhoan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="Int")]
		public System.Nullable<int> SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this._SoDienThoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TTLuuThong", DbType="Int")]
		public System.Nullable<int> TTLuuThong
		{
			get
			{
				return this._TTLuuThong;
			}
			set
			{
				if ((this._TTLuuThong != value))
				{
					this._TTLuuThong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TTThanhToan", DbType="Int")]
		public System.Nullable<int> TTThanhToan
		{
			get
			{
				return this._TTThanhToan;
			}
			set
			{
				if ((this._TTThanhToan != value))
				{
					this._TTThanhToan = value;
				}
			}
		}
	}
	
	public partial class getTaiKhoanResult
	{
		
		private int _MaKH;
		
		private int _MaTK;
		
		private string _MatKhau;
		
		private string _Email;
		
		public getTaiKhoanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int NOT NULL")]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this._MaKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK", DbType="Int NOT NULL")]
		public int MaTK
		{
			get
			{
				return this._MaTK;
			}
			set
			{
				if ((this._MaTK != value))
				{
					this._MaTK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this._MatKhau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
	}
	
	public partial class getTTLuuThongResult
	{
		
		private int _MaTT;
		
		private string _TenTT;
		
		public getTTLuuThongResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTT", DbType="Int NOT NULL")]
		public int MaTT
		{
			get
			{
				return this._MaTT;
			}
			set
			{
				if ((this._MaTT != value))
				{
					this._MaTT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTT", DbType="VarChar(50)")]
		public string TenTT
		{
			get
			{
				return this._TenTT;
			}
			set
			{
				if ((this._TenTT != value))
				{
					this._TenTT = value;
				}
			}
		}
	}
	
	public partial class getTTSuDungInternetResult
	{
		
		private int _MaKH;
		
		private int _MaTK;
		
		private System.DateTime _ThoiGianBatDau;
		
		private System.Nullable<System.DateTime> _ThoiGianKetThuc;
		
		private System.Nullable<double> _DungLuongSuDung;
		
		public getTTSuDungInternetResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int NOT NULL")]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this._MaKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTK", DbType="Int NOT NULL")]
		public int MaTK
		{
			get
			{
				return this._MaTK;
			}
			set
			{
				if ((this._MaTK != value))
				{
					this._MaTK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBatDau", DbType="DateTime NOT NULL")]
		public System.DateTime ThoiGianBatDau
		{
			get
			{
				return this._ThoiGianBatDau;
			}
			set
			{
				if ((this._ThoiGianBatDau != value))
				{
					this._ThoiGianBatDau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianKetThuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianKetThuc
		{
			get
			{
				return this._ThoiGianKetThuc;
			}
			set
			{
				if ((this._ThoiGianKetThuc != value))
				{
					this._ThoiGianKetThuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DungLuongSuDung", DbType="Float")]
		public System.Nullable<double> DungLuongSuDung
		{
			get
			{
				return this._DungLuongSuDung;
			}
			set
			{
				if ((this._DungLuongSuDung != value))
				{
					this._DungLuongSuDung = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
